/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "salle_callbacks.h"
#include "salle_interface.h"
#include "../common/support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_GestionSalle (void)
{
  GtkWidget *GestionSalle;
  GtkWidget *fixed1;
  GtkWidget *entry36;
  GtkWidget *label173;
  GtkWidget *label160;
  GtkWidget *button32;
  GtkWidget *alignment26;
  GtkWidget *hbox74;
  GtkWidget *image25;
  GtkWidget *label161;
  GtkWidget *button34;
  GtkWidget *alignment28;
  GtkWidget *hbox76;
  GtkWidget *label175;
  GtkWidget *image27;
  GtkWidget *button33;
  GtkWidget *alignment27;
  GtkWidget *hbox75;
  GtkWidget *label174;
  GtkWidget *image26;
  GtkWidget *scrolledwindow3;
  GtkWidget *treeview3;

  GestionSalle = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (GestionSalle, 1300, 550);
  gtk_window_set_title (GTK_WINDOW (GestionSalle), _("Gestion des salles de sports"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (GestionSalle), fixed1);
  gtk_widget_set_size_request (fixed1, 750, -1);

  entry36 = gtk_entry_new ();
  gtk_widget_show (entry36);
  gtk_fixed_put (GTK_FIXED (fixed1), entry36, 192, 40);
  gtk_widget_set_size_request (entry36, 500, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry36), 8226);

  label173 = gtk_label_new (_("Gestion des salles du sport"));
  gtk_widget_show (label173);
  gtk_fixed_put (GTK_FIXED (fixed1), label173, 280, 0);
  gtk_widget_set_size_request (label173, 199, 32);
  gtk_label_set_justify (GTK_LABEL (label173), GTK_JUSTIFY_CENTER);

  label160 = gtk_label_new (_("Rechercher : "));
  gtk_widget_show (label160);
  gtk_fixed_put (GTK_FIXED (fixed1), label160, 32, 48);
  gtk_widget_set_size_request (label160, 100, 18);

  button32 = gtk_button_new ();
  gtk_widget_show (button32);
  gtk_fixed_put (GTK_FIXED (fixed1), button32, 24, 120);
  gtk_widget_set_size_request (button32, 100, 34);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (button32), alignment26);

  hbox74 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox74);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox74);

  image25 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox74), image25, FALSE, FALSE, 0);

  label161 = gtk_label_new_with_mnemonic (_(" Ajouter"));
  gtk_widget_show (label161);
  gtk_box_pack_start (GTK_BOX (hbox74), label161, FALSE, FALSE, 0);

  button34 = gtk_button_new ();
  gtk_widget_show (button34);
  gtk_fixed_put (GTK_FIXED (fixed1), button34, 496, 432);
  gtk_widget_set_size_request (button34, 104, 40);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (button34), alignment28);

  hbox76 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox76);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox76);

  label175 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label175);
  gtk_box_pack_start (GTK_BOX (hbox76), label175, FALSE, FALSE, 0);

  image27 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox76), image27, FALSE, FALSE, 0);

  button33 = gtk_button_new ();
  gtk_widget_show (button33);
  gtk_fixed_put (GTK_FIXED (fixed1), button33, 280, 432);
  gtk_widget_set_size_request (button33, 96, 40);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (button33), alignment27);

  hbox75 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox75);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox75);

  label174 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label174);
  gtk_box_pack_start (GTK_BOX (hbox75), label174, FALSE, FALSE, 0);

  image26 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox75), image26, FALSE, FALSE, 0);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_fixed_put (GTK_FIXED (fixed1), scrolledwindow3, 32, 192);
  gtk_widget_set_size_request (scrolledwindow3, 1150, 200);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_ALWAYS, GTK_POLICY_ALWAYS);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_SHADOW_NONE);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), treeview3);
  gtk_tree_view_set_enable_search (GTK_TREE_VIEW (treeview3), TRUE);

  g_signal_connect ((gpointer) entry36, "changed",
                    G_CALLBACK (salle_on_entry36_changed),
                    NULL);
  g_signal_connect ((gpointer) button32, "clicked",
                    G_CALLBACK (salle_on_button32_clicked),
                    NULL);
  g_signal_connect ((gpointer) button34, "clicked",
                    G_CALLBACK (salle_on_button34_clicked),
                    NULL);
  g_signal_connect ((gpointer) button33, "clicked",
                    G_CALLBACK (salle_on_button33_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GestionSalle, GestionSalle, "GestionSalle");
  GLADE_HOOKUP_OBJECT (GestionSalle, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (GestionSalle, entry36, "entry36");
  GLADE_HOOKUP_OBJECT (GestionSalle, label173, "label173");
  GLADE_HOOKUP_OBJECT (GestionSalle, label160, "label160");
  GLADE_HOOKUP_OBJECT (GestionSalle, button32, "button32");
  GLADE_HOOKUP_OBJECT (GestionSalle, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (GestionSalle, hbox74, "hbox74");
  GLADE_HOOKUP_OBJECT (GestionSalle, image25, "image25");
  GLADE_HOOKUP_OBJECT (GestionSalle, label161, "label161");
  GLADE_HOOKUP_OBJECT (GestionSalle, button34, "button34");
  GLADE_HOOKUP_OBJECT (GestionSalle, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (GestionSalle, hbox76, "hbox76");
  GLADE_HOOKUP_OBJECT (GestionSalle, label175, "label175");
  GLADE_HOOKUP_OBJECT (GestionSalle, image27, "image27");
  GLADE_HOOKUP_OBJECT (GestionSalle, button33, "button33");
  GLADE_HOOKUP_OBJECT (GestionSalle, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (GestionSalle, hbox75, "hbox75");
  GLADE_HOOKUP_OBJECT (GestionSalle, label174, "label174");
  GLADE_HOOKUP_OBJECT (GestionSalle, image26, "image26");
  GLADE_HOOKUP_OBJECT (GestionSalle, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (GestionSalle, treeview3, "treeview3");

  return GestionSalle;
}

GtkWidget*
create_AjoutSalle (void)
{
  GtkWidget *AjoutSalle;
  GtkWidget *fixed;
  GtkWidget *label, *entry37, *entry38, *entry39, *entry40, *entry41, *entry43;
  GtkWidget *spinbutton1, *spinbutton2;
  GtkWidget *checkbutton1, *checkbutton2, *checkbutton3, *checkbutton4;
  GtkWidget *radiobutton1, *radiobutton2;
  GtkWidget *button35, *button36;
  GtkWidget *optionmenu1, *menu1, *menuitem;

  AjoutSalle = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (AjoutSalle), _("Ajouter une salle"));
  gtk_widget_set_size_request (AjoutSalle, 600, 700);
  gtk_window_set_position (GTK_WINDOW (AjoutSalle), GTK_WIN_POS_CENTER);

  fixed = gtk_fixed_new ();
  gtk_container_add (GTK_CONTAINER (AjoutSalle), fixed);

  /* Labels and entries */
  int y = 20;
  label = gtk_label_new ("Nom:");
  gtk_fixed_put (GTK_FIXED (fixed), label, 20, y);
  entry37 = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed), entry37, 150, y);
  gtk_widget_set_size_request (entry37, 400, 25);

  y += 40;
  label = gtk_label_new ("Adresse:");
  gtk_fixed_put (GTK_FIXED (fixed), label, 20, y);
  entry38 = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed), entry38, 150, y);
  gtk_widget_set_size_request (entry38, 400, 25);

  y += 40;
  label = gtk_label_new ("Téléphone:");
  gtk_fixed_put (GTK_FIXED (fixed), label, 20, y);
  entry39 = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed), entry39, 150, y);
  gtk_widget_set_size_request (entry39, 200, 25);

  y += 40;
  label = gtk_label_new ("Email:");
  gtk_fixed_put (GTK_FIXED (fixed), label, 20, y);
  entry40 = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed), entry40, 150, y);
  gtk_widget_set_size_request (entry40, 300, 25);

  y += 40;
  label = gtk_label_new ("Heure début (HH:MM):");
  gtk_fixed_put (GTK_FIXED (fixed), label, 20, y);
  entry41 = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed), entry41, 150, y);
  gtk_widget_set_size_request (entry41, 100, 25);

  y += 40;
  label = gtk_label_new ("Heure fin (HH:MM):");
  gtk_fixed_put (GTK_FIXED (fixed), label, 20, y);
  entry43 = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed), entry43, 150, y);
  gtk_widget_set_size_request (entry43, 100, 25);

  y += 40;
  label = gtk_label_new ("Capacité:");
  gtk_fixed_put (GTK_FIXED (fixed), label, 20, y);
  spinbutton1 = gtk_spin_button_new_with_range (0, 1000, 1);
  gtk_fixed_put (GTK_FIXED (fixed), spinbutton1, 150, y);

  y += 40;
  label = gtk_label_new ("Tarif (DT):");
  gtk_fixed_put (GTK_FIXED (fixed), label, 20, y);
  spinbutton2 = gtk_spin_button_new_with_range (0, 10000, 0.5);
  gtk_spin_button_set_digits (GTK_SPIN_BUTTON (spinbutton2), 2);
  gtk_fixed_put (GTK_FIXED (fixed), spinbutton2, 150, y);

  y += 40;
  label = gtk_label_new ("Mode de paiement:");
  gtk_fixed_put (GTK_FIXED (fixed), label, 20, y);
  optionmenu1 = gtk_option_menu_new ();
  menu1 = gtk_menu_new ();
  menuitem = gtk_menu_item_new_with_label ("Espece");
  g_signal_connect (menuitem, "activate", G_CALLBACK (salle_on_esp__ce1_activate), NULL);
  gtk_menu_shell_append (GTK_MENU_SHELL (menu1), menuitem);
  menuitem = gtk_menu_item_new_with_label ("Cheque");
  g_signal_connect (menuitem, "activate", G_CALLBACK (salle_on_ch__que1_activate), NULL);
  gtk_menu_shell_append (GTK_MENU_SHELL (menu1), menuitem);
  menuitem = gtk_menu_item_new_with_label ("Carte Bancaire");
  g_signal_connect (menuitem, "activate", G_CALLBACK (salle_on_cartebancaire1_activate), NULL);
  gtk_menu_shell_append (GTK_MENU_SHELL (menu1), menuitem);
  menuitem = gtk_menu_item_new_with_label ("Virement");
  g_signal_connect (menuitem, "activate", G_CALLBACK (salle_on_virement1_activate), NULL);
  gtk_menu_shell_append (GTK_MENU_SHELL (menu1), menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (optionmenu1), menu1);
  gtk_fixed_put (GTK_FIXED (fixed), optionmenu1, 150, y);

  y += 40;
  label = gtk_label_new ("Type abonnement:");
  gtk_fixed_put (GTK_FIXED (fixed), label, 20, y);
  checkbutton1 = gtk_check_button_new_with_label ("Mensuel");
  gtk_fixed_put (GTK_FIXED (fixed), checkbutton1, 150, y);
  checkbutton2 = gtk_check_button_new_with_label ("Trimestriel");
  gtk_fixed_put (GTK_FIXED (fixed), checkbutton2, 250, y);

  y += 30;
  checkbutton3 = gtk_check_button_new_with_label ("Annuel");
  gtk_fixed_put (GTK_FIXED (fixed), checkbutton3, 150, y);
  checkbutton4 = gtk_check_button_new_with_label ("Accès libre");
  gtk_fixed_put (GTK_FIXED (fixed), checkbutton4, 250, y);

  y += 40;
  label = gtk_label_new ("Espace restauration:");
  gtk_fixed_put (GTK_FIXED (fixed), label, 20, y);
  radiobutton1 = gtk_radio_button_new_with_label (NULL, "Oui");
  gtk_fixed_put (GTK_FIXED (fixed), radiobutton1, 150, y);
  radiobutton2 = gtk_radio_button_new_with_label_from_widget (GTK_RADIO_BUTTON (radiobutton1), "Non");
  gtk_fixed_put (GTK_FIXED (fixed), radiobutton2, 220, y);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton2), TRUE);

  y += 50;
  button35 = gtk_button_new_with_label ("Ajouter");
  gtk_fixed_put (GTK_FIXED (fixed), button35, 150, y);
  gtk_widget_set_size_request (button35, 100, 35);
  g_signal_connect (button35, "clicked", G_CALLBACK (salle_on_button35_clicked), NULL);

  button36 = gtk_button_new_with_label ("Annuler");
  gtk_fixed_put (GTK_FIXED (fixed), button36, 300, y);
  gtk_widget_set_size_request (button36, 100, 35);
  g_signal_connect (button36, "clicked", G_CALLBACK (salle_on_button36_clicked), NULL);

  gtk_widget_show_all (fixed);

  /* Store pointers to all widgets */
  GLADE_HOOKUP_OBJECT_NO_REF (AjoutSalle, AjoutSalle, "AjoutSalle");
  GLADE_HOOKUP_OBJECT (AjoutSalle, entry37, "entry37");
  GLADE_HOOKUP_OBJECT (AjoutSalle, entry38, "entry38");
  GLADE_HOOKUP_OBJECT (AjoutSalle, entry39, "entry39");
  GLADE_HOOKUP_OBJECT (AjoutSalle, entry40, "entry40");
  GLADE_HOOKUP_OBJECT (AjoutSalle, entry41, "entry41");
  GLADE_HOOKUP_OBJECT (AjoutSalle, entry43, "entry43");
  GLADE_HOOKUP_OBJECT (AjoutSalle, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (AjoutSalle, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (AjoutSalle, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (AjoutSalle, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (AjoutSalle, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (AjoutSalle, checkbutton4, "checkbutton4");
  GLADE_HOOKUP_OBJECT (AjoutSalle, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (AjoutSalle, radiobutton2, "radiobutton2");

  return AjoutSalle;
}

GtkWidget*
create_MOdiffSalle (void)
{
  GtkWidget *MOdiffSalle;
  GtkWidget *fixed;
  GtkWidget *label, *entry56, *entry57, *entry58, *entry59, *entry60, *entry61;
  GtkWidget *spinbutton21, *spinbutton22;
  GtkWidget *checkbutton5, *checkbutton6, *checkbutton7, *checkbutton8;
  GtkWidget *radiobutton10, *radiobutton11;
  GtkWidget *button46, *button47;
  GtkWidget *optionmenu2, *menu2, *menuitem;

  MOdiffSalle = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MOdiffSalle), _("Modifier une salle"));
  gtk_widget_set_size_request (MOdiffSalle, 600, 700);
  gtk_window_set_position (GTK_WINDOW (MOdiffSalle), GTK_WIN_POS_CENTER);

  fixed = gtk_fixed_new ();
  gtk_container_add (GTK_CONTAINER (MOdiffSalle), fixed);

  /* Labels and entries */
  int y = 20;
  label = gtk_label_new ("Nom:");
  gtk_fixed_put (GTK_FIXED (fixed), label, 20, y);
  entry56 = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed), entry56, 150, y);
  gtk_widget_set_size_request (entry56, 400, 25);

  y += 40;
  label = gtk_label_new ("Adresse:");
  gtk_fixed_put (GTK_FIXED (fixed), label, 20, y);
  entry57 = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed), entry57, 150, y);
  gtk_widget_set_size_request (entry57, 400, 25);

  y += 40;
  label = gtk_label_new ("Téléphone:");
  gtk_fixed_put (GTK_FIXED (fixed), label, 20, y);
  entry58 = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed), entry58, 150, y);
  gtk_widget_set_size_request (entry58, 200, 25);

  y += 40;
  label = gtk_label_new ("Email:");
  gtk_fixed_put (GTK_FIXED (fixed), label, 20, y);
  entry59 = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed), entry59, 150, y);
  gtk_widget_set_size_request (entry59, 300, 25);

  y += 40;
  label = gtk_label_new ("Heure début (HH:MM):");
  gtk_fixed_put (GTK_FIXED (fixed), label, 20, y);
  entry60 = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed), entry60, 150, y);
  gtk_widget_set_size_request (entry60, 100, 25);

  y += 40;
  label = gtk_label_new ("Heure fin (HH:MM):");
  gtk_fixed_put (GTK_FIXED (fixed), label, 20, y);
  entry61 = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed), entry61, 150, y);
  gtk_widget_set_size_request (entry61, 100, 25);

  y += 40;
  label = gtk_label_new ("Capacité:");
  gtk_fixed_put (GTK_FIXED (fixed), label, 20, y);
  spinbutton21 = gtk_spin_button_new_with_range (0, 1000, 1);
  gtk_fixed_put (GTK_FIXED (fixed), spinbutton21, 150, y);

  y += 40;
  label = gtk_label_new ("Tarif (DT):");
  gtk_fixed_put (GTK_FIXED (fixed), label, 20, y);
  spinbutton22 = gtk_spin_button_new_with_range (0, 10000, 0.5);
  gtk_spin_button_set_digits (GTK_SPIN_BUTTON (spinbutton22), 2);
  gtk_fixed_put (GTK_FIXED (fixed), spinbutton22, 150, y);

  y += 40;
  label = gtk_label_new ("Mode de paiement:");
  gtk_fixed_put (GTK_FIXED (fixed), label, 20, y);
  optionmenu2 = gtk_option_menu_new ();
  menu2 = gtk_menu_new ();
  menuitem = gtk_menu_item_new_with_label ("Espece");
  g_signal_connect (menuitem, "activate", G_CALLBACK (salle_on_esp__ce2_activate), NULL);
  gtk_menu_shell_append (GTK_MENU_SHELL (menu2), menuitem);
  menuitem = gtk_menu_item_new_with_label ("Cheque");
  g_signal_connect (menuitem, "activate", G_CALLBACK (salle_on_ch__que2_activate), NULL);
  gtk_menu_shell_append (GTK_MENU_SHELL (menu2), menuitem);
  menuitem = gtk_menu_item_new_with_label ("Carte Bancaire");
  g_signal_connect (menuitem, "activate", G_CALLBACK (salle_on_cartebancaire2_activate), NULL);
  gtk_menu_shell_append (GTK_MENU_SHELL (menu2), menuitem);
  menuitem = gtk_menu_item_new_with_label ("Virement");
  g_signal_connect (menuitem, "activate", G_CALLBACK (salle_on_virement2_activate), NULL);
  gtk_menu_shell_append (GTK_MENU_SHELL (menu2), menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (optionmenu2), menu2);
  gtk_fixed_put (GTK_FIXED (fixed), optionmenu2, 150, y);

  y += 40;
  label = gtk_label_new ("Type abonnement:");
  gtk_fixed_put (GTK_FIXED (fixed), label, 20, y);
  checkbutton5 = gtk_check_button_new_with_label ("Mensuel");
  gtk_fixed_put (GTK_FIXED (fixed), checkbutton5, 150, y);
  checkbutton6 = gtk_check_button_new_with_label ("Trimestriel");
  gtk_fixed_put (GTK_FIXED (fixed), checkbutton6, 250, y);

  y += 30;
  checkbutton7 = gtk_check_button_new_with_label ("Annuel");
  gtk_fixed_put (GTK_FIXED (fixed), checkbutton7, 150, y);
  checkbutton8 = gtk_check_button_new_with_label ("Accès libre");
  gtk_fixed_put (GTK_FIXED (fixed), checkbutton8, 250, y);

  y += 40;
  label = gtk_label_new ("Espace restauration:");
  gtk_fixed_put (GTK_FIXED (fixed), label, 20, y);
  radiobutton11 = gtk_radio_button_new_with_label (NULL, "Oui");
  gtk_fixed_put (GTK_FIXED (fixed), radiobutton11, 150, y);
  radiobutton10 = gtk_radio_button_new_with_label_from_widget (GTK_RADIO_BUTTON (radiobutton11), "Non");
  gtk_fixed_put (GTK_FIXED (fixed), radiobutton10, 220, y);

  y += 50;
  button46 = gtk_button_new_with_label ("Modifier");
  gtk_fixed_put (GTK_FIXED (fixed), button46, 150, y);
  gtk_widget_set_size_request (button46, 100, 35);
  g_signal_connect (button46, "clicked", G_CALLBACK (salle_on_button46_clicked), NULL);

  button47 = gtk_button_new_with_label ("Annuler");
  gtk_fixed_put (GTK_FIXED (fixed), button47, 300, y);
  gtk_widget_set_size_request (button47, 100, 35);

  gtk_widget_show_all (fixed);

  /* Store pointers to all widgets */
  GLADE_HOOKUP_OBJECT_NO_REF (MOdiffSalle, MOdiffSalle, "MOdiffSalle");
  GLADE_HOOKUP_OBJECT (MOdiffSalle, entry56, "entry56");
  GLADE_HOOKUP_OBJECT (MOdiffSalle, entry57, "entry57");
  GLADE_HOOKUP_OBJECT (MOdiffSalle, entry58, "entry58");
  GLADE_HOOKUP_OBJECT (MOdiffSalle, entry59, "entry59");
  GLADE_HOOKUP_OBJECT (MOdiffSalle, entry60, "entry60");
  GLADE_HOOKUP_OBJECT (MOdiffSalle, entry61, "entry61");
  GLADE_HOOKUP_OBJECT (MOdiffSalle, spinbutton21, "spinbutton21");
  GLADE_HOOKUP_OBJECT (MOdiffSalle, spinbutton22, "spinbutton22");
  GLADE_HOOKUP_OBJECT (MOdiffSalle, checkbutton5, "checkbutton5");
  GLADE_HOOKUP_OBJECT (MOdiffSalle, checkbutton6, "checkbutton6");
  GLADE_HOOKUP_OBJECT (MOdiffSalle, checkbutton7, "checkbutton7");
  GLADE_HOOKUP_OBJECT (MOdiffSalle, checkbutton8, "checkbutton8");
  GLADE_HOOKUP_OBJECT (MOdiffSalle, radiobutton10, "radiobutton10");
  GLADE_HOOKUP_OBJECT (MOdiffSalle, radiobutton11, "radiobutton11");
  GLADE_HOOKUP_OBJECT (MOdiffSalle, optionmenu2, "optionmenu2");

  return MOdiffSalle;
}

GtkWidget*
create_inscritsalle (void)
{
  GtkWidget *inscritsalle;
  GtkWidget *fixed;
  GtkWidget *label;
  GtkWidget *optionmenu3, *optionmenu4;
  GtkWidget *button_inscri, *button49;
  GtkWidget *scrolledwindow;
  GtkWidget *treeview4;

  inscritsalle = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (inscritsalle), _("Inscription salle"));
  gtk_widget_set_size_request (inscritsalle, 800, 600);
  gtk_window_set_position (GTK_WINDOW (inscritsalle), GTK_WIN_POS_CENTER);

  fixed = gtk_fixed_new ();
  gtk_container_add (GTK_CONTAINER (inscritsalle), fixed);

  int y = 20;
  label = gtk_label_new ("Entraîneur:");
  gtk_fixed_put (GTK_FIXED (fixed), label, 20, y);
  optionmenu3 = gtk_option_menu_new ();
  gtk_fixed_put (GTK_FIXED (fixed), optionmenu3, 150, y);
  gtk_widget_set_size_request (optionmenu3, 300, 30);

  y += 50;
  label = gtk_label_new ("Salle:");
  gtk_fixed_put (GTK_FIXED (fixed), label, 20, y);
  optionmenu4 = gtk_option_menu_new ();
  gtk_fixed_put (GTK_FIXED (fixed), optionmenu4, 150, y);
  gtk_widget_set_size_request (optionmenu4, 300, 30);

  y += 50;
  button_inscri = gtk_button_new_with_label ("Inscrire");
  gtk_fixed_put (GTK_FIXED (fixed), button_inscri, 150, y);
  gtk_widget_set_size_request (button_inscri, 100, 35);
  g_signal_connect (button_inscri, "clicked", G_CALLBACK (salle_on_inscri_salle_clicked), NULL);

  button49 = gtk_button_new_with_label ("Statistiques");
  gtk_fixed_put (GTK_FIXED (fixed), button49, 300, y);
  gtk_widget_set_size_request (button49, 120, 35);
  g_signal_connect (button49, "clicked", G_CALLBACK (salle_on_button49_clicked), NULL);

  y += 50;
  scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_fixed_put (GTK_FIXED (fixed), scrolledwindow, 20, y);
  gtk_widget_set_size_request (scrolledwindow, 760, 400);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  treeview4 = gtk_tree_view_new ();
  gtk_container_add (GTK_CONTAINER (scrolledwindow), treeview4);

  gtk_widget_show_all (fixed);

  /* Store pointers to all widgets */
  GLADE_HOOKUP_OBJECT_NO_REF (inscritsalle, inscritsalle, "inscritsalle");
  GLADE_HOOKUP_OBJECT (inscritsalle, optionmenu3, "optionmenu3");
  GLADE_HOOKUP_OBJECT (inscritsalle, optionmenu4, "optionmenu4");
  GLADE_HOOKUP_OBJECT (inscritsalle, treeview4, "treeview4");

  return inscritsalle;
}