/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ajouter_entraineur (void);
GtkWidget* create_modifier_entraineur (void);
GtkWidget* create_inscription_entraineur (void);
