/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ajouter_entraineur (void)
{
  GtkWidget *ajouter_entraineur;
  GtkWidget *fixed1;
  GtkWidget *label2;
  GtkWidget *entry1;
  GtkWidget *label3;
  GtkWidget *entry2;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *label4;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *comboboxentry1;
  GtkWidget *label5;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label6;
  GtkWidget *button2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label7;
  GtkWidget *label1;

  ajouter_entraineur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter_entraineur), _("ajouter_entraineur"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (ajouter_entraineur), fixed1);

  label2 = gtk_label_new (_("Nom"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 0, 48);
  gtk_widget_set_size_request (label2, 56, 16);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 56, 40);
  gtk_widget_set_size_request (entry1, 264, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  label3 = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 0, 80);
  gtk_widget_set_size_request (label3, 72, 24);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 80, 80);
  gtk_widget_set_size_request (entry2, 248, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton1, 136, 120);
  gtk_widget_set_size_request (spinbutton1, 70, 35);

  label4 = gtk_label_new (_("Date de naissance\n"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 0, 128);
  gtk_widget_set_size_request (label4, 136, 24);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton2, 216, 120);
  gtk_widget_set_size_request (spinbutton2, 70, 35);

  spinbutton3_adj = gtk_adjustment_new (1, 1900, 2025, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton3, 296, 120);
  gtk_widget_set_size_request (spinbutton3, 70, 35);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxentry1, 88, 168);
  gtk_widget_set_size_request (comboboxentry1, 207, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("gymnastique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("box"));
  gtk_combo_box_set_add_tearoffs (GTK_COMBO_BOX (comboboxentry1), TRUE);

  label5 = gtk_label_new (_("Sp\303\251cialit\303\251"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 0, 176);
  gtk_widget_set_size_request (label5, 88, 24);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 32, 248);
  gtk_widget_set_size_request (button1, 120, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox1), label6, FALSE, FALSE, 0);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 200, 248);
  gtk_widget_set_size_request (button2, 128, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox2), label7, FALSE, FALSE, 0);

  label1 = gtk_label_new (_("Ajouter un entraineur"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 64, 8);
  gtk_widget_set_size_request (label1, 248, 16);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter_entraineur, ajouter_entraineur, "ajouter_entraineur");
  GLADE_HOOKUP_OBJECT (ajouter_entraineur, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (ajouter_entraineur, label2, "label2");
  GLADE_HOOKUP_OBJECT (ajouter_entraineur, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (ajouter_entraineur, label3, "label3");
  GLADE_HOOKUP_OBJECT (ajouter_entraineur, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (ajouter_entraineur, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (ajouter_entraineur, label4, "label4");
  GLADE_HOOKUP_OBJECT (ajouter_entraineur, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (ajouter_entraineur, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (ajouter_entraineur, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (ajouter_entraineur, label5, "label5");
  GLADE_HOOKUP_OBJECT (ajouter_entraineur, button1, "button1");
  GLADE_HOOKUP_OBJECT (ajouter_entraineur, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (ajouter_entraineur, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (ajouter_entraineur, image1, "image1");
  GLADE_HOOKUP_OBJECT (ajouter_entraineur, label6, "label6");
  GLADE_HOOKUP_OBJECT (ajouter_entraineur, button2, "button2");
  GLADE_HOOKUP_OBJECT (ajouter_entraineur, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (ajouter_entraineur, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (ajouter_entraineur, image2, "image2");
  GLADE_HOOKUP_OBJECT (ajouter_entraineur, label7, "label7");
  GLADE_HOOKUP_OBJECT (ajouter_entraineur, label1, "label1");

  return ajouter_entraineur;
}

GtkWidget*
create_modifier_entraineur (void)
{
  GtkWidget *modifier_entraineur;
  GtkWidget *fixed4;
  GtkWidget *label15;
  GtkWidget *entry4;
  GtkWidget *label16;
  GtkWidget *entry5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *label17;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkObject *spinbutton8_adj;
  GtkWidget *spinbutton8;
  GtkWidget *comboboxentry2;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *button7;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label21;
  GtkWidget *button6;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label20;

  modifier_entraineur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier_entraineur), _("modifier_entraineur"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (modifier_entraineur), fixed4);

  label15 = gtk_label_new (_("Nom"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed4), label15, 0, 48);
  gtk_widget_set_size_request (label15, 56, 16);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed4), entry4, 56, 40);
  gtk_widget_set_size_request (entry4, 264, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  label16 = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 0, 80);
  gtk_widget_set_size_request (label16, 72, 24);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed4), entry5, 80, 80);
  gtk_widget_set_size_request (entry5, 248, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  spinbutton6_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton6, 136, 120);
  gtk_widget_set_size_request (spinbutton6, 70, 35);

  label17 = gtk_label_new (_("Date de naissance\n"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed4), label17, 0, 128);
  gtk_widget_set_size_request (label17, 136, 24);

  spinbutton7_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton7, 216, 120);
  gtk_widget_set_size_request (spinbutton7, 70, 35);

  spinbutton8_adj = gtk_adjustment_new (1, 1900, 2025, 1, 10, 10);
  spinbutton8 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton8_adj), 1, 0);
  gtk_widget_show (spinbutton8);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton8, 296, 120);
  gtk_widget_set_size_request (spinbutton8, 70, 35);

  comboboxentry2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry2);
  gtk_fixed_put (GTK_FIXED (fixed4), comboboxentry2, 88, 168);
  gtk_widget_set_size_request (comboboxentry2, 207, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("gymnastique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("box"));
  gtk_combo_box_set_add_tearoffs (GTK_COMBO_BOX (comboboxentry2), TRUE);

  label18 = gtk_label_new (_("Sp\303\251cialit\303\251"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed4), label18, 0, 176);
  gtk_widget_set_size_request (label18, 88, 24);

  label19 = gtk_label_new (_("Modifier un entraineur"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 64, 8);
  gtk_widget_set_size_request (label19, 248, 16);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed4), button7, 200, 240);
  gtk_widget_set_size_request (button7, 128, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button7), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox6), label21, FALSE, FALSE, 0);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed4), button6, 32, 240);
  gtk_widget_set_size_request (button6, 120, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button6), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_icon_name ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (image5), 0.54, 0.5);

  label20 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox5), label20, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0.5, 0.49);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_entraineur, modifier_entraineur, "modifier_entraineur");
  GLADE_HOOKUP_OBJECT (modifier_entraineur, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (modifier_entraineur, label15, "label15");
  GLADE_HOOKUP_OBJECT (modifier_entraineur, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (modifier_entraineur, label16, "label16");
  GLADE_HOOKUP_OBJECT (modifier_entraineur, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (modifier_entraineur, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (modifier_entraineur, label17, "label17");
  GLADE_HOOKUP_OBJECT (modifier_entraineur, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (modifier_entraineur, spinbutton8, "spinbutton8");
  GLADE_HOOKUP_OBJECT (modifier_entraineur, comboboxentry2, "comboboxentry2");
  GLADE_HOOKUP_OBJECT (modifier_entraineur, label18, "label18");
  GLADE_HOOKUP_OBJECT (modifier_entraineur, label19, "label19");
  GLADE_HOOKUP_OBJECT (modifier_entraineur, button7, "button7");
  GLADE_HOOKUP_OBJECT (modifier_entraineur, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (modifier_entraineur, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (modifier_entraineur, image6, "image6");
  GLADE_HOOKUP_OBJECT (modifier_entraineur, label21, "label21");
  GLADE_HOOKUP_OBJECT (modifier_entraineur, button6, "button6");
  GLADE_HOOKUP_OBJECT (modifier_entraineur, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (modifier_entraineur, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (modifier_entraineur, image5, "image5");
  GLADE_HOOKUP_OBJECT (modifier_entraineur, label20, "label20");

  return modifier_entraineur;
}

GtkWidget*
create_inscription_entraineur (void)
{
  GtkWidget *inscription_entraineur;
  GtkWidget *fixed9;
  GtkWidget *label22;
  GtkWidget *entry6;
  GtkWidget *label23;
  GtkWidget *entry7;
  GtkObject *spinbutton9_adj;
  GtkWidget *spinbutton9;
  GtkWidget *label24;
  GtkObject *spinbutton10_adj;
  GtkWidget *spinbutton10;
  GtkObject *spinbutton11_adj;
  GtkWidget *spinbutton11;
  GtkWidget *comboboxentry3;
  GtkWidget *button8;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label27;
  GtkWidget *button9;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label28;
  GtkWidget *label26;
  GtkWidget *label25;

  inscription_entraineur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (inscription_entraineur), _("modifier_entraineur"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (inscription_entraineur), fixed9);

  label22 = gtk_label_new (_("Nom"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed9), label22, 0, 48);
  gtk_widget_set_size_request (label22, 56, 16);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed9), entry6, 56, 40);
  gtk_widget_set_size_request (entry6, 264, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  label23 = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed9), label23, 0, 80);
  gtk_widget_set_size_request (label23, 72, 24);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed9), entry7, 80, 80);
  gtk_widget_set_size_request (entry7, 248, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  spinbutton9_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton9 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton9_adj), 1, 0);
  gtk_widget_show (spinbutton9);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton9, 136, 120);
  gtk_widget_set_size_request (spinbutton9, 70, 35);

  label24 = gtk_label_new (_("Date de naissance\n"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed9), label24, 0, 128);
  gtk_widget_set_size_request (label24, 136, 24);

  spinbutton10_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton10 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton10_adj), 1, 0);
  gtk_widget_show (spinbutton10);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton10, 216, 120);
  gtk_widget_set_size_request (spinbutton10, 70, 35);

  spinbutton11_adj = gtk_adjustment_new (1, 1900, 2025, 1, 10, 10);
  spinbutton11 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton11_adj), 1, 0);
  gtk_widget_show (spinbutton11);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton11, 296, 120);
  gtk_widget_set_size_request (spinbutton11, 70, 35);

  comboboxentry3 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry3);
  gtk_fixed_put (GTK_FIXED (fixed9), comboboxentry3, 88, 168);
  gtk_widget_set_size_request (comboboxentry3, 207, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("gymnastique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("box"));
  gtk_combo_box_set_add_tearoffs (GTK_COMBO_BOX (comboboxentry3), TRUE);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed9), button8, 200, 240);
  gtk_widget_set_size_request (button8, 128, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button8), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox7), label27, FALSE, FALSE, 0);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed9), button9, 32, 240);
  gtk_widget_set_size_request (button9, 120, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button9), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-connect", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (image8), 0.54, 0.5);

  label28 = gtk_label_new_with_mnemonic (_("s'inscrire"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox8), label28, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label28), 0.5, 0.49);

  label26 = gtk_label_new (_("Inscription \303\240 un cours sportif"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed9), label26, 64, 8);
  gtk_widget_set_size_request (label26, 248, 16);

  label25 = gtk_label_new (_("cours sportifs"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed9), label25, 0, 176);
  gtk_widget_set_size_request (label25, 88, 24);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (inscription_entraineur, inscription_entraineur, "inscription_entraineur");
  GLADE_HOOKUP_OBJECT (inscription_entraineur, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (inscription_entraineur, label22, "label22");
  GLADE_HOOKUP_OBJECT (inscription_entraineur, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (inscription_entraineur, label23, "label23");
  GLADE_HOOKUP_OBJECT (inscription_entraineur, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (inscription_entraineur, spinbutton9, "spinbutton9");
  GLADE_HOOKUP_OBJECT (inscription_entraineur, label24, "label24");
  GLADE_HOOKUP_OBJECT (inscription_entraineur, spinbutton10, "spinbutton10");
  GLADE_HOOKUP_OBJECT (inscription_entraineur, spinbutton11, "spinbutton11");
  GLADE_HOOKUP_OBJECT (inscription_entraineur, comboboxentry3, "comboboxentry3");
  GLADE_HOOKUP_OBJECT (inscription_entraineur, button8, "button8");
  GLADE_HOOKUP_OBJECT (inscription_entraineur, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (inscription_entraineur, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (inscription_entraineur, image7, "image7");
  GLADE_HOOKUP_OBJECT (inscription_entraineur, label27, "label27");
  GLADE_HOOKUP_OBJECT (inscription_entraineur, button9, "button9");
  GLADE_HOOKUP_OBJECT (inscription_entraineur, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (inscription_entraineur, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (inscription_entraineur, image8, "image8");
  GLADE_HOOKUP_OBJECT (inscription_entraineur, label28, "label28");
  GLADE_HOOKUP_OBJECT (inscription_entraineur, label26, "label26");
  GLADE_HOOKUP_OBJECT (inscription_entraineur, label25, "label25");

  return inscription_entraineur;
}

