/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "member_callbacks.h"
#include "member_interface.h"
#include "../common/support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *gm5;
  GtkWidget *gm9;
  GtkWidget *image29;
  GtkWidget *gm6;
  GtkWidget *gm12;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label8;
  GtkWidget *gm8;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label5;
  GtkWidget *gm10;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label6;
  GtkWidget *gm11;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label7;
  GtkWidget *button3;
  GtkWidget *gm1;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("Gestion des Membres - Salle de Sport"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  gm5 = gtk_entry_new ();
  gtk_widget_show (gm5);
  gtk_fixed_put (GTK_FIXED (fixed1), gm5, 64, 112);
  gtk_widget_set_size_request (gm5, 216, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (gm5), 8226);

  gm9 = gtk_tree_view_new ();
  gtk_widget_show (gm9);
  gtk_fixed_put (GTK_FIXED (fixed1), gm9, 0, 216);
  gtk_widget_set_size_request (gm9, 750, 280);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (gm9), TRUE);
  gtk_tree_view_set_hover_selection (GTK_TREE_VIEW (gm9), TRUE);

  image29 = create_pixmap (window1, "999cba9e-b1ce-4f71-a476-48cc364f217f.jpeg");
  gtk_widget_show (image29);
  gtk_fixed_put (GTK_FIXED (fixed1), image29, 0, -8);
  gtk_widget_set_size_request (image29, 752, 1024);

  gm6 = gtk_label_new (_("cin :             "));
  gtk_widget_show (gm6);
  gtk_fixed_put (GTK_FIXED (fixed1), gm6, 24, 112);
  gtk_widget_set_size_request (gm6, 43, 17);

  gm12 = gtk_button_new ();
  gtk_widget_show (gm12);
  gtk_fixed_put (GTK_FIXED (fixed1), gm12, 360, 80);
  gtk_widget_set_size_request (gm12, 112, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (gm12), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox4), label8, FALSE, FALSE, 0);

  gm8 = gtk_button_new ();
  gtk_widget_show (gm8);
  gtk_fixed_put (GTK_FIXED (fixed1), gm8, 360, 120);
  gtk_widget_set_size_request (gm8, 112, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (gm8), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Recherccher"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox1), label5, FALSE, FALSE, 0);

  gm10 = gtk_button_new ();
  gtk_widget_show (gm10);
  gtk_fixed_put (GTK_FIXED (fixed1), gm10, 360, 160);
  gtk_widget_set_size_request (gm10, 112, 37);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (gm10), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox2), label6, FALSE, FALSE, 0);

  gm11 = gtk_button_new ();
  gtk_widget_show (gm11);
  gtk_fixed_put (GTK_FIXED (fixed1), gm11, 568, 560);
  gtk_widget_set_size_request (gm11, 120, 77);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (gm11), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox3), label7, FALSE, FALSE, 0);

  button3 = gtk_button_new_with_mnemonic (_("coach privee"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed1), button3, 568, 648);
  gtk_widget_set_size_request (button3, 120, 77);

  gm1 = gtk_label_new (_("  Gestion des membres"));
  gtk_widget_show (gm1);
  gtk_fixed_put (GTK_FIXED (fixed1), gm1, 160, 24);
  gtk_widget_set_size_request (gm1, 280, 40);
  gtk_misc_set_alignment (GTK_MISC (gm1), 0.5, 0.48);

  g_signal_connect ((gpointer) gm9, "row-activated",
                    G_CALLBACK (member_on_treeview_row_activated),
                    NULL);
  g_signal_connect ((gpointer) gm12, "clicked",
                    G_CALLBACK (member_on_gm12_clicked),
                    NULL);
  g_signal_connect ((gpointer) gm8, "clicked",
                    G_CALLBACK (member_on_gm8_clicked),
                    NULL);
  g_signal_connect ((gpointer) gm10, "clicked",
                    G_CALLBACK (member_on_gm10_clicked),
                    NULL);
  g_signal_connect ((gpointer) gm11, "clicked",
                    G_CALLBACK (member_on_gm11_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, gm5, "gm5");
  GLADE_HOOKUP_OBJECT (window1, gm9, "gm9");
  GLADE_HOOKUP_OBJECT (window1, image29, "image29");
  GLADE_HOOKUP_OBJECT (window1, gm6, "gm6");
  GLADE_HOOKUP_OBJECT (window1, gm12, "gm12");
  GLADE_HOOKUP_OBJECT (window1, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window1, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window1, image4, "image4");
  GLADE_HOOKUP_OBJECT (window1, label8, "label8");
  GLADE_HOOKUP_OBJECT (window1, gm8, "gm8");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");
  GLADE_HOOKUP_OBJECT (window1, gm10, "gm10");
  GLADE_HOOKUP_OBJECT (window1, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1, image2, "image2");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, gm11, "gm11");
  GLADE_HOOKUP_OBJECT (window1, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window1, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window1, image3, "image3");
  GLADE_HOOKUP_OBJECT (window1, label7, "label7");
  GLADE_HOOKUP_OBJECT (window1, button3, "button3");
  GLADE_HOOKUP_OBJECT (window1, gm1, "gm1");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed2;
  GtkWidget *ajm6;
  GtkWidget *ajm7;
  GtkWidget *ajm8;
  GtkObject *ajm9_adj;
  GtkWidget *ajm9;
  GtkObject *ajm10_adj;
  GtkWidget *ajm10;
  GtkObject *ajm11_adj;
  GtkWidget *ajm11;
  GtkWidget *ajm13;
  GtkWidget *ajm15;
  GtkWidget *ajm17;
  GtkWidget *image21;
  GtkWidget *ajm1;
  GtkWidget *ajm3;
  GtkWidget *ajm4;
  GtkWidget *ajm2;
  GtkWidget *ajm5;
  GtkWidget *ajm12;
  GtkWidget *ajm14;
  GtkWidget *ajm16;
  GtkWidget *ajm20;
  GSList *ajm20_group = NULL;
  GtkWidget *ajm21;
  GtkWidget *ajm18;
  GtkWidget *ajm19;
  GtkWidget *ajm22;
  GtkWidget *ajm26;
  GtkWidget *ajm25;
  GtkWidget *ajm24;
  GtkWidget *ajm23;
  GtkWidget *ajm27;
  GtkWidget *ajm28;
  GtkWidget *ajm29;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image6;
  GtkWidget *label32;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("Ajouter un Nouveau Membre"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window2), fixed2);

  ajm6 = gtk_entry_new ();
  gtk_widget_show (ajm6);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm6, 64, 32);
  gtk_widget_set_size_request (ajm6, 224, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajm6), 8226);

  ajm7 = gtk_entry_new ();
  gtk_widget_show (ajm7);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm7, 64, 64);
  gtk_widget_set_size_request (ajm7, 224, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajm7), 8226);

  ajm8 = gtk_entry_new ();
  gtk_widget_show (ajm8);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm8, 64, 96);
  gtk_widget_set_size_request (ajm8, 224, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajm8), 8226);

  ajm9_adj = gtk_adjustment_new (2025, 1900, 2100, 1, 10, 10);
  ajm9 = gtk_spin_button_new (GTK_ADJUSTMENT (ajm9_adj), 1, 0);
  gtk_widget_show (ajm9);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm9, 232, 128);
  gtk_widget_set_size_request (ajm9, 70, 27);

  ajm10_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  ajm10 = gtk_spin_button_new (GTK_ADJUSTMENT (ajm10_adj), 1, 0);
  gtk_widget_show (ajm10);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm10, 184, 128);
  gtk_widget_set_size_request (ajm10, 48, 27);

  ajm11_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  ajm11 = gtk_spin_button_new (GTK_ADJUSTMENT (ajm11_adj), 1, 0);
  gtk_widget_show (ajm11);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm11, 136, 128);
  gtk_widget_set_size_request (ajm11, 48, 27);

  ajm13 = gtk_entry_new ();
  gtk_widget_show (ajm13);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm13, 272, 200);
  gtk_widget_set_size_request (ajm13, 104, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajm13), 8226);

  ajm15 = gtk_entry_new ();
  gtk_widget_show (ajm15);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm15, 64, 200);
  gtk_widget_set_size_request (ajm15, 96, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajm15), 8226);

  ajm17 = gtk_entry_new ();
  gtk_widget_show (ajm17);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm17, 64, 160);
  gtk_widget_set_size_request (ajm17, 224, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajm17), 8226);

  image21 = create_pixmap (window2, "8e671388-37f0-4f11-b741-49bf382a2dee.jpeg");
  gtk_widget_show (image21);
  gtk_fixed_put (GTK_FIXED (fixed2), image21, 0, 0);
  gtk_widget_set_size_request (image21, 456, 773);

  ajm1 = gtk_label_new (_("Ajouter un membre"));
  gtk_widget_show (ajm1);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm1, 120, 0);
  gtk_widget_set_size_request (ajm1, 176, 16);

  ajm3 = gtk_label_new (_("Pr\303\251nom:   "));
  gtk_widget_show (ajm3);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm3, 0, 64);
  gtk_widget_set_size_request (ajm3, 80, 16);

  ajm4 = gtk_label_new (_("Cin:        "));
  gtk_widget_show (ajm4);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm4, 0, 96);
  gtk_widget_set_size_request (ajm4, 65, 16);

  ajm2 = gtk_label_new (_("Nom:    "));
  gtk_widget_show (ajm2);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm2, 8, 32);
  gtk_widget_set_size_request (ajm2, 49, 17);

  ajm5 = gtk_label_new (_("Date de naissance:     "));
  gtk_widget_show (ajm5);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm5, 0, 128);
  gtk_widget_set_size_request (ajm5, 152, 24);

  ajm12 = gtk_label_new (_("E-Mail:            "));
  gtk_widget_show (ajm12);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm12, 0, 152);
  gtk_widget_set_size_request (ajm12, 89, 32);

  ajm14 = gtk_label_new (_("T\303\251l\303\251phone:"));
  gtk_widget_show (ajm14);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm14, 168, 200);
  gtk_widget_set_size_request (ajm14, 88, 32);

  ajm16 = gtk_label_new (_("Ville :    "));
  gtk_widget_show (ajm16);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm16, 8, 208);
  gtk_widget_set_size_request (ajm16, 49, 17);

  ajm20 = gtk_radio_button_new_with_mnemonic (NULL, _("Homme "));
  gtk_widget_show (ajm20);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm20, 0, 256);
  gtk_widget_set_size_request (ajm20, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ajm20), ajm20_group);
  ajm20_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ajm20));

  ajm21 = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (ajm21);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm21, 128, 256);
  gtk_widget_set_size_request (ajm21, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ajm21), ajm20_group);
  ajm20_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ajm21));

  ajm18 = gtk_label_new (_("abonnement"));
  gtk_widget_show (ajm18);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm18, 0, 304);
  gtk_widget_set_size_request (ajm18, 104, 17);

  ajm19 = gtk_combo_box_new_text ();
  gtk_widget_show (ajm19);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm19, 112, 296);
  gtk_widget_set_size_request (ajm19, 152, 33);
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajm19), _("1 mois"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajm19), _("3 mois"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajm19), _("1 an"));

  ajm22 = gtk_label_new (_("Quel sport\n vous int\303\251resse?"));
  gtk_widget_show (ajm22);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm22, 0, 368);
  gtk_widget_set_size_request (ajm22, 120, 40);

  ajm26 = gtk_check_button_new_with_mnemonic (_("Musculation"));
  gtk_widget_show (ajm26);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm26, 160, 360);
  gtk_widget_set_size_request (ajm26, 120, 24);

  ajm25 = gtk_check_button_new_with_mnemonic (_("Dance"));
  gtk_widget_show (ajm25);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm25, 160, 392);
  gtk_widget_set_size_request (ajm25, 118, 24);

  ajm24 = gtk_check_button_new_with_mnemonic (_("Aerobic"));
  gtk_widget_show (ajm24);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm24, 160, 424);
  gtk_widget_set_size_request (ajm24, 118, 24);

  ajm23 = gtk_check_button_new_with_mnemonic (_("Box anglaise"));
  gtk_widget_show (ajm23);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm23, 304, 360);
  gtk_widget_set_size_request (ajm23, 118, 24);

  ajm27 = gtk_check_button_new_with_mnemonic (_("Gymnastique"));
  gtk_widget_show (ajm27);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm27, 304, 392);
  gtk_widget_set_size_request (ajm27, 118, 24);

  ajm28 = gtk_check_button_new_with_mnemonic (_("Natation"));
  gtk_widget_show (ajm28);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm28, 304, 424);
  gtk_widget_set_size_request (ajm28, 118, 24);

  ajm29 = gtk_button_new ();
  gtk_widget_show (ajm29);
  gtk_fixed_put (GTK_FIXED (fixed2), ajm29, 288, 536);
  gtk_widget_set_size_request (ajm29, 152, 48);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (ajm29), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image6 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox5), image6, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Vlider"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox5), label32, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) ajm29, "clicked",
                    G_CALLBACK (member_on_ajm29_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2, ajm6, "ajm6");
  GLADE_HOOKUP_OBJECT (window2, ajm7, "ajm7");
  GLADE_HOOKUP_OBJECT (window2, ajm8, "ajm8");
  GLADE_HOOKUP_OBJECT (window2, ajm9, "ajm9");
  GLADE_HOOKUP_OBJECT (window2, ajm10, "ajm10");
  GLADE_HOOKUP_OBJECT (window2, ajm11, "ajm11");
  GLADE_HOOKUP_OBJECT (window2, ajm13, "ajm13");
  GLADE_HOOKUP_OBJECT (window2, ajm15, "ajm15");
  GLADE_HOOKUP_OBJECT (window2, ajm17, "ajm17");
  GLADE_HOOKUP_OBJECT (window2, image21, "image21");
  GLADE_HOOKUP_OBJECT (window2, ajm1, "ajm1");
  GLADE_HOOKUP_OBJECT (window2, ajm3, "ajm3");
  GLADE_HOOKUP_OBJECT (window2, ajm4, "ajm4");
  GLADE_HOOKUP_OBJECT (window2, ajm2, "ajm2");
  GLADE_HOOKUP_OBJECT (window2, ajm5, "ajm5");
  GLADE_HOOKUP_OBJECT (window2, ajm12, "ajm12");
  GLADE_HOOKUP_OBJECT (window2, ajm14, "ajm14");
  GLADE_HOOKUP_OBJECT (window2, ajm16, "ajm16");
  GLADE_HOOKUP_OBJECT (window2, ajm20, "ajm20");
  GLADE_HOOKUP_OBJECT (window2, ajm21, "ajm21");
  GLADE_HOOKUP_OBJECT (window2, ajm18, "ajm18");
  GLADE_HOOKUP_OBJECT (window2, ajm19, "ajm19");
  GLADE_HOOKUP_OBJECT (window2, ajm22, "ajm22");
  GLADE_HOOKUP_OBJECT (window2, ajm26, "ajm26");
  GLADE_HOOKUP_OBJECT (window2, ajm25, "ajm25");
  GLADE_HOOKUP_OBJECT (window2, ajm24, "ajm24");
  GLADE_HOOKUP_OBJECT (window2, ajm23, "ajm23");
  GLADE_HOOKUP_OBJECT (window2, ajm27, "ajm27");
  GLADE_HOOKUP_OBJECT (window2, ajm28, "ajm28");
  GLADE_HOOKUP_OBJECT (window2, ajm29, "ajm29");
  GLADE_HOOKUP_OBJECT (window2, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window2, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window2, image6, "image6");
  GLADE_HOOKUP_OBJECT (window2, label32, "label32");

  gtk_widget_grab_focus (ajm9);
  return window2;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *fixed3;
  GtkWidget *modm6;
  GtkWidget *modm7;
  GtkWidget *modm8;
  GtkObject *modm9_adj;
  GtkWidget *modm9;
  GtkObject *modm10_adj;
  GtkWidget *modm10;
  GtkObject *modm11_adj;
  GtkWidget *modm11;
  GtkWidget *modm13;
  GtkWidget *modm15;
  GtkWidget *modm17;
  GtkWidget *image22;
  GtkWidget *modm1;
  GtkWidget *modm2;
  GtkWidget *modm3;
  GtkWidget *modm4;
  GtkWidget *modm5;
  GtkWidget *modm12;
  GtkWidget *modm16;
  GtkWidget *modm14;
  GtkWidget *modm18;
  GtkWidget *modm19;
  GtkWidget *modm22;
  GtkWidget *modm25;
  GtkWidget *modm28;
  GtkWidget *modm26;
  GtkWidget *modm23;
  GtkWidget *modm27;
  GtkWidget *modm24;
  GtkWidget *modm20;
  GSList *modm20_group = NULL;
  GtkWidget *modm21;
  GSList *modm21_group = NULL;
  GtkWidget *modm29;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image8;
  GtkWidget *label43;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3), _("Modifier les Informations d'un Membre"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window3), fixed3);

  modm6 = gtk_entry_new ();
  gtk_widget_show (modm6);
  gtk_fixed_put (GTK_FIXED (fixed3), modm6, 72, 32);
  gtk_widget_set_size_request (modm6, 304, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modm6), 8226);

  modm7 = gtk_entry_new ();
  gtk_widget_show (modm7);
  gtk_fixed_put (GTK_FIXED (fixed3), modm7, 72, 64);
  gtk_widget_set_size_request (modm7, 304, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modm7), 8226);

  modm8 = gtk_entry_new ();
  gtk_widget_show (modm8);
  gtk_fixed_put (GTK_FIXED (fixed3), modm8, 72, 96);
  gtk_widget_set_size_request (modm8, 304, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modm8), 8226);

  modm9_adj = gtk_adjustment_new (2025, 1900, 2100, 1, 10, 10);
  modm9 = gtk_spin_button_new (GTK_ADJUSTMENT (modm9_adj), 1, 0);
  gtk_widget_show (modm9);
  gtk_fixed_put (GTK_FIXED (fixed3), modm9, 136, 128);
  gtk_widget_set_size_request (modm9, 80, 27);

  modm10_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  modm10 = gtk_spin_button_new (GTK_ADJUSTMENT (modm10_adj), 1, 0);
  gtk_widget_show (modm10);
  gtk_fixed_put (GTK_FIXED (fixed3), modm10, 192, 128);
  gtk_widget_set_size_request (modm10, 60, 27);

  modm11_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  modm11 = gtk_spin_button_new (GTK_ADJUSTMENT (modm11_adj), 1, 0);
  gtk_widget_show (modm11);
  gtk_fixed_put (GTK_FIXED (fixed3), modm11, 248, 128);
  gtk_widget_set_size_request (modm11, 48, 27);

  modm13 = gtk_entry_new ();
  gtk_widget_show (modm13);
  gtk_fixed_put (GTK_FIXED (fixed3), modm13, 248, 192);
  gtk_widget_set_size_request (modm13, 136, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modm13), 8226);

  modm15 = gtk_entry_new ();
  gtk_widget_show (modm15);
  gtk_fixed_put (GTK_FIXED (fixed3), modm15, 48, 192);
  gtk_widget_set_size_request (modm15, 96, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modm15), 8226);

  modm17 = gtk_entry_new ();
  gtk_widget_show (modm17);
  gtk_fixed_put (GTK_FIXED (fixed3), modm17, 72, 160);
  gtk_widget_set_size_request (modm17, 304, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modm17), 8226);

  image22 = create_pixmap (window3, "8e671388-37f0-4f11-b741-49bf382a2dee.jpeg");
  gtk_widget_show (image22);
  gtk_fixed_put (GTK_FIXED (fixed3), image22, 0, 0);
  gtk_widget_set_size_request (image22, 456, 800);

  modm1 = gtk_label_new (_("Modifier les information d' un membre"));
  gtk_widget_show (modm1);
  gtk_fixed_put (GTK_FIXED (fixed3), modm1, 56, 0);
  gtk_widget_set_size_request (modm1, 304, 23);

  modm2 = gtk_label_new (_("Nom:    "));
  gtk_widget_show (modm2);
  gtk_fixed_put (GTK_FIXED (fixed3), modm2, 8, 32);
  gtk_widget_set_size_request (modm2, 49, 17);

  modm3 = gtk_label_new (_("Pr\303\251nom:   "));
  gtk_widget_show (modm3);
  gtk_fixed_put (GTK_FIXED (fixed3), modm3, 0, 64);
  gtk_widget_set_size_request (modm3, 80, 16);

  modm4 = gtk_label_new (_("Cin:        "));
  gtk_widget_show (modm4);
  gtk_fixed_put (GTK_FIXED (fixed3), modm4, 0, 96);
  gtk_widget_set_size_request (modm4, 65, 16);

  modm5 = gtk_label_new (_("Date de naissance:"));
  gtk_widget_show (modm5);
  gtk_fixed_put (GTK_FIXED (fixed3), modm5, 0, 128);
  gtk_widget_set_size_request (modm5, 136, 24);

  modm12 = gtk_label_new (_("E-Mail:          "));
  gtk_widget_show (modm12);
  gtk_fixed_put (GTK_FIXED (fixed3), modm12, 0, 160);
  gtk_widget_set_size_request (modm12, 88, 24);

  modm16 = gtk_label_new (_("Ville :    "));
  gtk_widget_show (modm16);
  gtk_fixed_put (GTK_FIXED (fixed3), modm16, 8, 192);
  gtk_widget_set_size_request (modm16, 48, 25);

  modm14 = gtk_label_new (_("T\303\251l\303\251phone:"));
  gtk_widget_show (modm14);
  gtk_fixed_put (GTK_FIXED (fixed3), modm14, 160, 192);
  gtk_widget_set_size_request (modm14, 88, 24);

  modm18 = gtk_label_new (_("abonnement"));
  gtk_widget_show (modm18);
  gtk_fixed_put (GTK_FIXED (fixed3), modm18, 0, 240);
  gtk_widget_set_size_request (modm18, 104, 17);

  modm19 = gtk_combo_box_new_text ();
  gtk_widget_show (modm19);
  gtk_fixed_put (GTK_FIXED (fixed3), modm19, 104, 240);
  gtk_widget_set_size_request (modm19, 152, 33);
  gtk_combo_box_append_text (GTK_COMBO_BOX (modm19), _("1 mois"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modm19), _("3 mois"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modm19), _("1 an"));

  modm22 = gtk_label_new (_("Quel sport\n vous int\303\251resse?"));
  gtk_widget_show (modm22);
  gtk_fixed_put (GTK_FIXED (fixed3), modm22, 0, 320);
  gtk_widget_set_size_request (modm22, 144, 40);

  modm25 = gtk_check_button_new_with_mnemonic (_("Dance"));
  gtk_widget_show (modm25);
  gtk_fixed_put (GTK_FIXED (fixed3), modm25, 176, 312);
  gtk_widget_set_size_request (modm25, 118, 24);

  modm28 = gtk_check_button_new_with_mnemonic (_("Natation"));
  gtk_widget_show (modm28);
  gtk_fixed_put (GTK_FIXED (fixed3), modm28, 176, 344);
  gtk_widget_set_size_request (modm28, 118, 24);

  modm26 = gtk_check_button_new_with_mnemonic (_("Musculation"));
  gtk_widget_show (modm26);
  gtk_fixed_put (GTK_FIXED (fixed3), modm26, 176, 384);
  gtk_widget_set_size_request (modm26, 126, 16);

  modm23 = gtk_check_button_new_with_mnemonic (_("Box anglaise"));
  gtk_widget_show (modm23);
  gtk_fixed_put (GTK_FIXED (fixed3), modm23, 312, 312);
  gtk_widget_set_size_request (modm23, 118, 24);

  modm27 = gtk_check_button_new_with_mnemonic (_("Gymnastique"));
  gtk_widget_show (modm27);
  gtk_fixed_put (GTK_FIXED (fixed3), modm27, 312, 344);
  gtk_widget_set_size_request (modm27, 118, 24);

  modm24 = gtk_check_button_new_with_mnemonic (_("Aerobic"));
  gtk_widget_show (modm24);
  gtk_fixed_put (GTK_FIXED (fixed3), modm24, 312, 384);
  gtk_widget_set_size_request (modm24, 118, 24);

  modm20 = gtk_radio_button_new_with_mnemonic (NULL, _("Homme "));
  gtk_widget_show (modm20);
  gtk_fixed_put (GTK_FIXED (fixed3), modm20, 8, 288);
  gtk_widget_set_size_request (modm20, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (modm20), modm20_group);
  modm20_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (modm20));

  modm21 = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (modm21);
  gtk_fixed_put (GTK_FIXED (fixed3), modm21, 160, 288);
  gtk_widget_set_size_request (modm21, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (modm21), modm21_group);
  modm21_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (modm21));

  modm29 = gtk_button_new ();
  gtk_widget_show (modm29);
  gtk_fixed_put (GTK_FIXED (fixed3), modm29, 272, 440);
  gtk_widget_set_size_request (modm29, 164, 77);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (modm29), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image8 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox6), image8, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("Vlider"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox6), label43, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) modm29, "clicked",
                    G_CALLBACK (member_on_modm29_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window3, modm6, "modm6");
  GLADE_HOOKUP_OBJECT (window3, modm7, "modm7");
  GLADE_HOOKUP_OBJECT (window3, modm8, "modm8");
  GLADE_HOOKUP_OBJECT (window3, modm9, "modm9");
  GLADE_HOOKUP_OBJECT (window3, modm10, "modm10");
  GLADE_HOOKUP_OBJECT (window3, modm11, "modm11");
  GLADE_HOOKUP_OBJECT (window3, modm13, "modm13");
  GLADE_HOOKUP_OBJECT (window3, modm15, "modm15");
  GLADE_HOOKUP_OBJECT (window3, modm17, "modm17");
  GLADE_HOOKUP_OBJECT (window3, image22, "image22");
  GLADE_HOOKUP_OBJECT (window3, modm1, "modm1");
  GLADE_HOOKUP_OBJECT (window3, modm2, "modm2");
  GLADE_HOOKUP_OBJECT (window3, modm3, "modm3");
  GLADE_HOOKUP_OBJECT (window3, modm4, "modm4");
  GLADE_HOOKUP_OBJECT (window3, modm5, "modm5");
  GLADE_HOOKUP_OBJECT (window3, modm12, "modm12");
  GLADE_HOOKUP_OBJECT (window3, modm16, "modm16");
  GLADE_HOOKUP_OBJECT (window3, modm14, "modm14");
  GLADE_HOOKUP_OBJECT (window3, modm18, "modm18");
  GLADE_HOOKUP_OBJECT (window3, modm19, "modm19");
  GLADE_HOOKUP_OBJECT (window3, modm22, "modm22");
  GLADE_HOOKUP_OBJECT (window3, modm25, "modm25");
  GLADE_HOOKUP_OBJECT (window3, modm28, "modm28");
  GLADE_HOOKUP_OBJECT (window3, modm26, "modm26");
  GLADE_HOOKUP_OBJECT (window3, modm23, "modm23");
  GLADE_HOOKUP_OBJECT (window3, modm27, "modm27");
  GLADE_HOOKUP_OBJECT (window3, modm24, "modm24");
  GLADE_HOOKUP_OBJECT (window3, modm20, "modm20");
  GLADE_HOOKUP_OBJECT (window3, modm21, "modm21");
  GLADE_HOOKUP_OBJECT (window3, modm29, "modm29");
  GLADE_HOOKUP_OBJECT (window3, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window3, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window3, image8, "image8");
  GLADE_HOOKUP_OBJECT (window3, label43, "label43");

  gtk_widget_grab_focus (modm9);
  return window3;
}

GtkWidget*
create_window4 (void)
{
  GtkWidget *window4;
  GtkWidget *fixed4;
  GtkWidget *image30;
  GtkWidget *vasup1;
  GtkWidget *vasup2;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image10;
  GtkWidget *label45;
  GtkWidget *vasup3;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image11;
  GtkWidget *label46;

  window4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window4), _("Affichage des S\303\251ances"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (window4), fixed4);

  image30 = create_pixmap (window4, "010b99fe-76e8-4163-b338-1ed2c9fb3b97.jpeg");
  gtk_widget_show (image30);
  gtk_fixed_put (GTK_FIXED (fixed4), image30, 0, 0);
  gtk_widget_set_size_request (image30, 557, 333);

  vasup1 = gtk_label_new (_("Vous souhaitez supprimeer les informations?"));
  gtk_widget_show (vasup1);
  gtk_fixed_put (GTK_FIXED (fixed4), vasup1, 224, 24);
  gtk_widget_set_size_request (vasup1, 312, 64);

  vasup2 = gtk_button_new ();
  gtk_widget_show (vasup2);
  gtk_fixed_put (GTK_FIXED (fixed4), vasup2, 248, 112);
  gtk_widget_set_size_request (vasup2, 112, 48);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (vasup2), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox7), image10, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("oui"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox7), label45, FALSE, FALSE, 0);

  vasup3 = gtk_button_new ();
  gtk_widget_show (vasup3);
  gtk_fixed_put (GTK_FIXED (fixed4), vasup3, 392, 112);
  gtk_widget_set_size_request (vasup3, 120, 48);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (vasup3), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image11 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox8), image11, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("non"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox8), label46, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4, window4, "window4");
  GLADE_HOOKUP_OBJECT (window4, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window4, image30, "image30");
  GLADE_HOOKUP_OBJECT (window4, vasup1, "vasup1");
  GLADE_HOOKUP_OBJECT (window4, vasup2, "vasup2");
  GLADE_HOOKUP_OBJECT (window4, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window4, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window4, image10, "image10");
  GLADE_HOOKUP_OBJECT (window4, label45, "label45");
  GLADE_HOOKUP_OBJECT (window4, vasup3, "vasup3");
  GLADE_HOOKUP_OBJECT (window4, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window4, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window4, image11, "image11");
  GLADE_HOOKUP_OBJECT (window4, label46, "label46");

  return window4;
}

GtkWidget*
create_window5 (void)
{
  GtkWidget *window5;
  GtkWidget *fixed5;
  GtkWidget *fixed6;
  GtkWidget *image25;
  GtkWidget *vamodm1;
  GtkWidget *vamodm2;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image12;
  GtkWidget *label47;
  GtkWidget *vamodm3;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image13;
  GtkWidget *label48;

  window5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window5), _("Recherche Avanc\303\251e"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window5), fixed5);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_fixed_put (GTK_FIXED (fixed5), fixed6, 0, 0);
  gtk_widget_set_size_request (fixed6, 600, 368);

  image25 = create_pixmap (window5, "010b99fe-76e8-4163-b338-1ed2c9fb3b97.jpeg");
  gtk_widget_show (image25);
  gtk_fixed_put (GTK_FIXED (fixed6), image25, 0, 0);
  gtk_widget_set_size_request (image25, 600, 368);

  vamodm1 = gtk_label_new (_("Vous souhaitez modifier les informations?"));
  gtk_widget_show (vamodm1);
  gtk_fixed_put (GTK_FIXED (fixed6), vamodm1, 256, 0);
  gtk_widget_set_size_request (vamodm1, 304, 88);

  vamodm2 = gtk_button_new ();
  gtk_widget_show (vamodm2);
  gtk_fixed_put (GTK_FIXED (fixed6), vamodm2, 272, 112);
  gtk_widget_set_size_request (vamodm2, 82, 48);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (vamodm2), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image12 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox9), image12, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("oui"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox9), label47, FALSE, FALSE, 0);

  vamodm3 = gtk_button_new ();
  gtk_widget_show (vamodm3);
  gtk_fixed_put (GTK_FIXED (fixed6), vamodm3, 408, 112);
  gtk_widget_set_size_request (vamodm3, 88, 45);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (vamodm3), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image13 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox10), image13, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("non"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox10), label48, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5, window5, "window5");
  GLADE_HOOKUP_OBJECT (window5, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window5, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window5, image25, "image25");
  GLADE_HOOKUP_OBJECT (window5, vamodm1, "vamodm1");
  GLADE_HOOKUP_OBJECT (window5, vamodm2, "vamodm2");
  GLADE_HOOKUP_OBJECT (window5, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window5, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window5, image12, "image12");
  GLADE_HOOKUP_OBJECT (window5, label47, "label47");
  GLADE_HOOKUP_OBJECT (window5, vamodm3, "vamodm3");
  GLADE_HOOKUP_OBJECT (window5, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window5, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window5, image13, "image13");
  GLADE_HOOKUP_OBJECT (window5, label48, "label48");

  return window5;
}

GtkWidget*
create_window6 (void)
{
  GtkWidget *window6;
  GtkWidget *fixed7;
  GtkWidget *fixed8;
  GtkWidget *image23;
  GtkWidget *valajm1;
  GtkWidget *valam2;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image14;
  GtkWidget *label50;
  GtkWidget *valajm3;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image15;
  GtkWidget *label51;

  window6 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window6), _("Statistiques et Rapports"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window6), fixed7);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_fixed_put (GTK_FIXED (fixed7), fixed8, 0, 0);
  gtk_widget_set_size_request (fixed8, 608, 376);

  image23 = create_pixmap (window6, "010b99fe-76e8-4163-b338-1ed2c9fb3b97.jpeg");
  gtk_widget_show (image23);
  gtk_fixed_put (GTK_FIXED (fixed8), image23, 0, 0);
  gtk_widget_set_size_request (image23, 608, 376);

  valajm1 = gtk_label_new (_("Vous souhaitez ajouter le membre?"));
  gtk_widget_show (valajm1);
  gtk_fixed_put (GTK_FIXED (fixed8), valajm1, 272, 32);
  gtk_widget_set_size_request (valajm1, 304, 88);

  valam2 = gtk_button_new ();
  gtk_widget_show (valam2);
  gtk_fixed_put (GTK_FIXED (fixed8), valam2, 264, 144);
  gtk_widget_set_size_request (valam2, 144, 48);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (valam2), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image14 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox11), image14, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("oui"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox11), label50, FALSE, FALSE, 0);

  valajm3 = gtk_button_new ();
  gtk_widget_show (valajm3);
  gtk_fixed_put (GTK_FIXED (fixed8), valajm3, 448, 144);
  gtk_widget_set_size_request (valajm3, 136, 48);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (valajm3), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image15 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox12), image15, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("non"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox12), label51, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window6, window6, "window6");
  GLADE_HOOKUP_OBJECT (window6, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window6, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window6, image23, "image23");
  GLADE_HOOKUP_OBJECT (window6, valajm1, "valajm1");
  GLADE_HOOKUP_OBJECT (window6, valam2, "valam2");
  GLADE_HOOKUP_OBJECT (window6, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window6, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window6, image14, "image14");
  GLADE_HOOKUP_OBJECT (window6, label50, "label50");
  GLADE_HOOKUP_OBJECT (window6, valajm3, "valajm3");
  GLADE_HOOKUP_OBJECT (window6, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window6, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window6, image15, "image15");
  GLADE_HOOKUP_OBJECT (window6, label51, "label51");

  return window6;
}

GtkWidget*
create_window7 (void)
{
  GtkWidget *window7;
  GtkWidget *fixed10;
  GtkWidget *combobox4;
  GtkWidget *cp5;
  GtkWidget *cp6;
  GtkWidget *cp7;
  GtkWidget *image27;
  GtkWidget *cp2;
  GtkWidget *cp3;
  GtkWidget *cp4;
  GtkWidget *cp8;
  GSList *cp8_group = NULL;
  GtkWidget *cp9;
  GSList *cp9_group = NULL;
  GtkWidget *cp10;
  GtkWidget *cp12;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image16;
  GtkWidget *label76;
  GtkWidget *cp1;
  GtkWidget *cp11;

  window7 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window7), _("Param\303\250tres de l'Application"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (window7), fixed10);

  combobox4 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox4);
  gtk_fixed_put (GTK_FIXED (fixed10), combobox4, 152, 272);
  gtk_widget_set_size_request (combobox4, 33, 31);

  cp5 = gtk_entry_new ();
  gtk_widget_show (cp5);
  gtk_fixed_put (GTK_FIXED (fixed10), cp5, 96, 64);
  gtk_widget_set_size_request (cp5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cp5), 8226);

  cp6 = gtk_entry_new ();
  gtk_widget_show (cp6);
  gtk_fixed_put (GTK_FIXED (fixed10), cp6, 96, 104);
  gtk_widget_set_size_request (cp6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cp6), 8226);

  cp7 = gtk_entry_new ();
  gtk_widget_show (cp7);
  gtk_fixed_put (GTK_FIXED (fixed10), cp7, 96, 144);
  gtk_widget_set_size_request (cp7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cp7), 8226);

  image27 = create_pixmap (window7, "999cba9e-b1ce-4f71-a476-48cc364f217f.jpeg");
  gtk_widget_show (image27);
  gtk_fixed_put (GTK_FIXED (fixed10), image27, 0, 0);
  gtk_widget_set_size_request (image27, 472, 824);

  cp2 = gtk_label_new (_("nom:     "));
  gtk_widget_show (cp2);
  gtk_fixed_put (GTK_FIXED (fixed10), cp2, 8, 64);
  gtk_widget_set_size_request (cp2, 49, 17);

  cp3 = gtk_label_new (_("pr\303\251nom: "));
  gtk_widget_show (cp3);
  gtk_fixed_put (GTK_FIXED (fixed10), cp3, 8, 104);
  gtk_widget_set_size_request (cp3, 56, 16);

  cp4 = gtk_label_new (_("cin:         "));
  gtk_widget_show (cp4);
  gtk_fixed_put (GTK_FIXED (fixed10), cp4, 8, 144);
  gtk_widget_set_size_request (cp4, 49, 17);

  cp8 = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (cp8);
  gtk_fixed_put (GTK_FIXED (fixed10), cp8, 0, 208);
  gtk_widget_set_size_request (cp8, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (cp8), cp8_group);
  cp8_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (cp8));

  cp9 = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (cp9);
  gtk_fixed_put (GTK_FIXED (fixed10), cp9, 144, 208);
  gtk_widget_set_size_request (cp9, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (cp9), cp9_group);
  cp9_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (cp9));

  cp10 = gtk_label_new (_("nom de coach:"));
  gtk_widget_show (cp10);
  gtk_fixed_put (GTK_FIXED (fixed10), cp10, 0, 272);
  gtk_widget_set_size_request (cp10, 104, 25);

  cp12 = gtk_button_new ();
  gtk_widget_show (cp12);
  gtk_fixed_put (GTK_FIXED (fixed10), cp12, 280, 80);
  gtk_widget_set_size_request (cp12, 176, 69);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (cp12), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image16 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox13), image16, FALSE, FALSE, 0);

  label76 = gtk_label_new_with_mnemonic (_("Valider "));
  gtk_widget_show (label76);
  gtk_box_pack_start (GTK_BOX (hbox13), label76, FALSE, FALSE, 0);

  cp1 = gtk_label_new (_("coach priv\303\251"));
  gtk_widget_show (cp1);
  gtk_fixed_put (GTK_FIXED (fixed10), cp1, 40, 0);
  gtk_widget_set_size_request (cp1, 304, 56);

  cp11 = gtk_combo_box_new_text ();
  gtk_widget_show (cp11);
  gtk_fixed_put (GTK_FIXED (fixed10), cp11, 128, 272);
  gtk_widget_set_size_request (cp11, 256, 47);
  gtk_combo_box_append_text (GTK_COMBO_BOX (cp11), _("ahmed ben mabrouk"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cp11), _("sirine nafati"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cp11), _("amine lajmi"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window7, window7, "window7");
  GLADE_HOOKUP_OBJECT (window7, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (window7, combobox4, "combobox4");
  GLADE_HOOKUP_OBJECT (window7, cp5, "cp5");
  GLADE_HOOKUP_OBJECT (window7, cp6, "cp6");
  GLADE_HOOKUP_OBJECT (window7, cp7, "cp7");
  GLADE_HOOKUP_OBJECT (window7, image27, "image27");
  GLADE_HOOKUP_OBJECT (window7, cp2, "cp2");
  GLADE_HOOKUP_OBJECT (window7, cp3, "cp3");
  GLADE_HOOKUP_OBJECT (window7, cp4, "cp4");
  GLADE_HOOKUP_OBJECT (window7, cp8, "cp8");
  GLADE_HOOKUP_OBJECT (window7, cp9, "cp9");
  GLADE_HOOKUP_OBJECT (window7, cp10, "cp10");
  GLADE_HOOKUP_OBJECT (window7, cp12, "cp12");
  GLADE_HOOKUP_OBJECT (window7, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window7, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window7, image16, "image16");
  GLADE_HOOKUP_OBJECT (window7, label76, "label76");
  GLADE_HOOKUP_OBJECT (window7, cp1, "cp1");
  GLADE_HOOKUP_OBJECT (window7, cp11, "cp11");

  return window7;
}

GtkWidget*
create_window8 (void)
{
  GtkWidget *window8;
  GtkWidget *fixed11;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkWidget *image17;
  GtkWidget *label83;
  GtkWidget *valideraffichage;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image18;
  GtkWidget *label79;

  window8 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window8), _("Gestion des Abonnements"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (window8), fixed11);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed11), entry1, 144, 56);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed11), entry2, 144, 88);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed11), entry3, 144, 120);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed11), entry4, 192, 152);
  gtk_widget_set_size_request (entry4, 112, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed11), entry5, 144, 184);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed11), entry6, 144, 216);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed11), entry7, 144, 248);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed11), entry8, 160, 288);
  gtk_widget_set_size_request (entry8, 144, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed11), entry9, 144, 320);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  image17 = create_pixmap (window8, "8e671388-37f0-4f11-b741-49bf382a2dee.jpeg");
  gtk_widget_show (image17);
  gtk_fixed_put (GTK_FIXED (fixed11), image17, 0, 0);
  gtk_widget_set_size_request (image17, 368, 664);

  label83 = gtk_label_new (_("nom:\n\nprenom:\n\ncin:\n\ndate de naissance:\n\ne-mail:\n\ntelephone :\n\nville :\n\nabonnement :\n\nsport:"));
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed11), label83, 40, 48);
  gtk_widget_set_size_request (label83, 128, 304);

  valideraffichage = gtk_button_new ();
  gtk_widget_show (valideraffichage);
  gtk_fixed_put (GTK_FIXED (fixed11), valideraffichage, 104, 384);
  gtk_widget_set_size_request (valideraffichage, 120, 56);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (valideraffichage), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image18 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox14), image18, FALSE, FALSE, 0);

  label79 = gtk_label_new_with_mnemonic (_("ok"));
  gtk_widget_show (label79);
  gtk_box_pack_start (GTK_BOX (hbox14), label79, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) valideraffichage, "clicked",
                    G_CALLBACK (member_on_valideraffichage_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window8, window8, "window8");
  GLADE_HOOKUP_OBJECT (window8, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (window8, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window8, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window8, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window8, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window8, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window8, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window8, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (window8, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (window8, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (window8, image17, "image17");
  GLADE_HOOKUP_OBJECT (window8, label83, "label83");
  GLADE_HOOKUP_OBJECT (window8, valideraffichage, "valideraffichage");
  GLADE_HOOKUP_OBJECT (window8, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window8, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window8, image18, "image18");
  GLADE_HOOKUP_OBJECT (window8, label79, "label79");

  return window8;
}

GtkWidget*
create_window9 (void)
{
  GtkWidget *window9;
  GtkWidget *fixed12;
  GtkWidget *image24;
  GtkWidget *label86;
  GtkWidget *button2;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image19;
  GtkWidget *label87;

  window9 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window9), _("Message de Confirmation"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (window9), fixed12);

  image24 = create_pixmap (window9, "010b99fe-76e8-4163-b338-1ed2c9fb3b97.jpeg");
  gtk_widget_show (image24);
  gtk_fixed_put (GTK_FIXED (fixed12), image24, 0, 0);
  gtk_widget_set_size_request (image24, 592, 384);

  label86 = gtk_label_new (_("membre introuvable"));
  gtk_widget_show (label86);
  gtk_fixed_put (GTK_FIXED (fixed12), label86, 280, 16);
  gtk_widget_set_size_request (label86, 153, 64);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed12), button2, 288, 112);
  gtk_widget_set_size_request (button2, 146, 61);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button2), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image19 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox15), image19, FALSE, FALSE, 0);

  label87 = gtk_label_new_with_mnemonic (_("ok"));
  gtk_widget_show (label87);
  gtk_box_pack_start (GTK_BOX (hbox15), label87, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (member_on_button2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window9, window9, "window9");
  GLADE_HOOKUP_OBJECT (window9, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (window9, image24, "image24");
  GLADE_HOOKUP_OBJECT (window9, label86, "label86");
  GLADE_HOOKUP_OBJECT (window9, button2, "button2");
  GLADE_HOOKUP_OBJECT (window9, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window9, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window9, image19, "image19");
  GLADE_HOOKUP_OBJECT (window9, label87, "label87");

  return window9;
}

