/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_page_d_acceuil (void);
GtkWidget* create_page_d_acceuil2 (void);
GtkWidget* create_window1 (void);
GtkWidget* create_window1 (void);
GtkWidget* create_window2 (void);
GtkWidget* create_window3 (void);
GtkWidget* create_window1 (void);
GtkWidget* create_page_d_acceuil_GE (void);
GtkWidget* create_ajouter_entraineur (void);
GtkWidget* create_modifier_entraineur (void);
GtkWidget* create_inscription_entraineur (void);
GtkWidget* create_cour_sportif_acceuil (void);
GtkWidget* create_inscrit_cour (void);
GtkWidget* create_ajouter_cour (void);
GtkWidget* create_modifer_cour (void);
GtkWidget* create_equipments_ajouter (void);
GtkWidget* create_equipment_main (void);
GtkWidget* create_equipments_modifier (void);
GtkWidget* create_reserver_equipments (void);
GtkWidget* create_GestionSalle (void);
GtkWidget* create_suppDailogue (void);
GtkWidget* create_AjoutSalle (void);
GtkWidget* create_inscritsalle (void);
GtkWidget* create_MOdiffSalle (void);
