/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_admincitoyen (void);
GtkWidget* create_gerer (void);
GtkWidget* create_gererparking (void);
GtkWidget* create_ajoutdeparking (void);
GtkWidget* create_supprimerparking (void);
GtkWidget* create_modifierparking (void);
GtkWidget* create_afficherparking (void);
GtkWidget* create_gereraffectation_ (void);
GtkWidget* create_ajoutagent_ (void);
GtkWidget* create_affecteragent_ (void);
GtkWidget* create_afficheraffectation_ (void);
GtkWidget* create_espace_citoyen (void);
GtkWidget* create_ajoutclient__ (void);
GtkWidget* create_suppressioncitoyen (void);
GtkWidget* create_login (void);
GtkWidget* create_afficher_citoyen (void);
GtkWidget* create_calculer_facture (void);
GtkWidget* create_modifiercitoyen (void);
GtkWidget* create_logincitoyen (void);
