/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *admincitoyen;
  GtkWidget *gererparking;
  GtkWidget *ajoutdeparking;
  GtkWidget *supprimerparking;
  GtkWidget *modifierparking;
  GtkWidget *afficherparking;
  GtkWidget *ajoutagent_;
  GtkWidget *affecteragent_;
  GtkWidget *afficheraffectation_ ;
  GtkWidget *gereraffectation_;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);
  add_pixmap_directory("../pixmaps");

/*  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");*/

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  gererparking = create_gererparking ();
 
  ajoutdeparking = create_ajoutdeparking ();
  
  supprimerparking = create_supprimerparking ();
  
  modifierparking = create_modifierparking ();
  
  afficherparking = create_afficherparking ();
 
  ajoutagent_ = create_ajoutagent_ ();
 
  affecteragent_ = create_affecteragent_ ();
 
  afficheraffectation_ = create_afficheraffectation_ ();
   
  gereraffectation_ = create_gereraffectation_ ();

 admincitoyen = create_admincitoyen ();
   gtk_widget_show (admincitoyen);
  gtk_main ();
  return 0;
}

