/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "course_callbacks.h"
#include "course_interface.h"
#include "../common/support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_page_d_acceuil (void)
{
  GtkWidget *page_d_acceuil;
  GtkWidget *notebook1;
  GtkWidget *fixed10;
  GtkWidget *entry36;
  GtkWidget *entry37;
  GtkWidget *calendar1;
  GtkWidget *button30;
  GtkWidget *alignment26;
  GtkWidget *hbox74;
  GtkWidget *image25;
  GtkWidget *label166;
  GtkWidget *button29;
  GtkWidget *alignment25;
  GtkWidget *hbox73;
  GtkWidget *image24;
  GtkWidget *label165;
  GtkWidget *comboboxentry4;
  GtkWidget *label163;
  GtkWidget *label162;
  GtkWidget *label164;
  GtkWidget *admin_acceuil;
  GtkWidget *fixed11;
  GtkWidget *entry38;
  GtkWidget *entry39;
  GtkWidget *calendar2;
  GtkWidget *button31;
  GtkWidget *alignment27;
  GtkWidget *hbox75;
  GtkWidget *image26;
  GtkWidget *label167;
  GtkWidget *button32;
  GtkWidget *alignment28;
  GtkWidget *hbox76;
  GtkWidget *image27;
  GtkWidget *label168;
  GtkWidget *comboboxentry5;
  GtkWidget *label169;
  GtkWidget *label170;
  GtkWidget *label171;
  GtkWidget *entraineur_acceuil;
  GtkWidget *fixed12;
  GtkWidget *entry40;
  GtkWidget *entry41;
  GtkWidget *calendar3;
  GtkWidget *button34;
  GtkWidget *alignment30;
  GtkWidget *hbox78;
  GtkWidget *image29;
  GtkWidget *label173;
  GtkWidget *comboboxentry6;
  GtkWidget *label174;
  GtkWidget *label175;
  GtkWidget *label176;
  GtkWidget *button33;
  GtkWidget *alignment29;
  GtkWidget *hbox77;
  GtkWidget *image28;
  GtkWidget *label172;
  GtkWidget *membre_acceuil;

  page_d_acceuil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (page_d_acceuil), _("page d'acceuil"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (page_d_acceuil), notebook1);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed10);

  entry36 = gtk_entry_new ();
  gtk_widget_show (entry36);
  gtk_fixed_put (GTK_FIXED (fixed10), entry36, 184, 112);
  gtk_widget_set_size_request (entry36, 184, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry36), 8226);

  entry37 = gtk_entry_new ();
  gtk_widget_show (entry37);
  gtk_fixed_put (GTK_FIXED (fixed10), entry37, 184, 208);
  gtk_widget_set_size_request (entry37, 184, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry37), 8226);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed10), calendar1, 480, 160);
  gtk_widget_set_size_request (calendar1, 162, 186);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  button30 = gtk_button_new ();
  gtk_widget_show (button30);
  gtk_fixed_put (GTK_FIXED (fixed10), button30, 88, 440);
  gtk_widget_set_size_request (button30, 96, 32);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (button30), alignment26);

  hbox74 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox74);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox74);

  image25 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox74), image25, FALSE, FALSE, 0);

  label166 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label166);
  gtk_box_pack_start (GTK_BOX (hbox74), label166, FALSE, FALSE, 0);

  button29 = gtk_button_new ();
  gtk_widget_show (button29);
  gtk_fixed_put (GTK_FIXED (fixed10), button29, 392, 448);
  gtk_widget_set_size_request (button29, 112, 32);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (button29), alignment25);

  hbox73 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox73);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox73);

  image24 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox73), image24, FALSE, FALSE, 0);

  label165 = gtk_label_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (label165);
  gtk_box_pack_start (GTK_BOX (hbox73), label165, FALSE, FALSE, 0);

  comboboxentry4 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry4);
  gtk_fixed_put (GTK_FIXED (fixed10), comboboxentry4, 184, 304);
  gtk_widget_set_size_request (comboboxentry4, 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("gestion des membres"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("gestion des entraineurs"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("gestion des cours sportifs"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("gestion des equipements"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("gestion des centres"));

  label163 = gtk_label_new (_("<b>mot de passe</b>"));
  gtk_widget_show (label163);
  gtk_fixed_put (GTK_FIXED (fixed10), label163, 48, 200);
  gtk_widget_set_size_request (label163, 104, 32);
  gtk_label_set_use_markup (GTK_LABEL (label163), TRUE);

  label162 = gtk_label_new (_("<b>identifiant</b>"));
  gtk_widget_show (label162);
  gtk_fixed_put (GTK_FIXED (fixed10), label162, 48, 104);
  gtk_widget_set_size_request (label162, 96, 32);
  gtk_label_set_use_markup (GTK_LABEL (label162), TRUE);

  label164 = gtk_label_new (_("<span font=\"poppins bold 18\">Page d'admin </span>"));
  gtk_widget_show (label164);
  gtk_fixed_put (GTK_FIXED (fixed10), label164, 240, 24);
  gtk_widget_set_size_request (label164, 192, 32);
  gtk_label_set_use_markup (GTK_LABEL (label164), TRUE);

  admin_acceuil = gtk_label_new (_("admin"));
  gtk_widget_show (admin_acceuil);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), admin_acceuil);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed11);
  gtk_widget_set_size_request (fixed11, 700, 550);

  entry38 = gtk_entry_new ();
  gtk_widget_show (entry38);
  gtk_fixed_put (GTK_FIXED (fixed11), entry38, 184, 128);
  gtk_widget_set_size_request (entry38, 184, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry38), 8226);

  entry39 = gtk_entry_new ();
  gtk_widget_show (entry39);
  gtk_fixed_put (GTK_FIXED (fixed11), entry39, 184, 216);
  gtk_widget_set_size_request (entry39, 184, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry39), 8226);

  calendar2 = gtk_calendar_new ();
  gtk_widget_show (calendar2);
  gtk_fixed_put (GTK_FIXED (fixed11), calendar2, 480, 160);
  gtk_widget_set_size_request (calendar2, 162, 186);
  gtk_calendar_display_options (GTK_CALENDAR (calendar2),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  button31 = gtk_button_new ();
  gtk_widget_show (button31);
  gtk_fixed_put (GTK_FIXED (fixed11), button31, 384, 432);
  gtk_widget_set_size_request (button31, 112, 32);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (button31), alignment27);

  hbox75 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox75);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox75);

  image26 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox75), image26, FALSE, FALSE, 0);

  label167 = gtk_label_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (label167);
  gtk_box_pack_start (GTK_BOX (hbox75), label167, FALSE, FALSE, 0);

  button32 = gtk_button_new ();
  gtk_widget_show (button32);
  gtk_fixed_put (GTK_FIXED (fixed11), button32, 96, 432);
  gtk_widget_set_size_request (button32, 96, 32);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (button32), alignment28);

  hbox76 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox76);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox76);

  image27 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox76), image27, FALSE, FALSE, 0);

  label168 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label168);
  gtk_box_pack_start (GTK_BOX (hbox76), label168, FALSE, FALSE, 0);

  comboboxentry5 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry5);
  gtk_fixed_put (GTK_FIXED (fixed11), comboboxentry5, 184, 304);
  gtk_widget_set_size_request (comboboxentry5, 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("inscrire a un centre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("rejoindre un cour "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("reserver  des equipements"));

  label169 = gtk_label_new (_("<b>mot de passe</b>"));
  gtk_widget_show (label169);
  gtk_fixed_put (GTK_FIXED (fixed11), label169, 56, 216);
  gtk_widget_set_size_request (label169, 104, 32);
  gtk_label_set_use_markup (GTK_LABEL (label169), TRUE);

  label170 = gtk_label_new (_("<b>identifiant</b>"));
  gtk_widget_show (label170);
  gtk_fixed_put (GTK_FIXED (fixed11), label170, 48, 120);
  gtk_widget_set_size_request (label170, 96, 32);
  gtk_label_set_use_markup (GTK_LABEL (label170), TRUE);

  label171 = gtk_label_new (_("<span font=\"poppins bold 18\">Page d'entraineur</span>"));
  gtk_widget_show (label171);
  gtk_fixed_put (GTK_FIXED (fixed11), label171, 200, 32);
  gtk_widget_set_size_request (label171, 256, 32);
  gtk_label_set_use_markup (GTK_LABEL (label171), TRUE);

  entraineur_acceuil = gtk_label_new (_("entraineur"));
  gtk_widget_show (entraineur_acceuil);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), entraineur_acceuil);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed12);
  gtk_widget_set_size_request (fixed12, 700, 550);

  entry40 = gtk_entry_new ();
  gtk_widget_show (entry40);
  gtk_fixed_put (GTK_FIXED (fixed12), entry40, 200, 136);
  gtk_widget_set_size_request (entry40, 184, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry40), 8226);

  entry41 = gtk_entry_new ();
  gtk_widget_show (entry41);
  gtk_fixed_put (GTK_FIXED (fixed12), entry41, 200, 216);
  gtk_widget_set_size_request (entry41, 184, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry41), 8226);

  calendar3 = gtk_calendar_new ();
  gtk_widget_show (calendar3);
  gtk_fixed_put (GTK_FIXED (fixed12), calendar3, 496, 152);
  gtk_widget_set_size_request (calendar3, 162, 186);
  gtk_calendar_display_options (GTK_CALENDAR (calendar3),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  button34 = gtk_button_new ();
  gtk_widget_show (button34);
  gtk_fixed_put (GTK_FIXED (fixed12), button34, 88, 440);
  gtk_widget_set_size_request (button34, 96, 32);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (button34), alignment30);

  hbox78 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox78);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox78);

  image29 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox78), image29, FALSE, FALSE, 0);

  label173 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label173);
  gtk_box_pack_start (GTK_BOX (hbox78), label173, FALSE, FALSE, 0);

  comboboxentry6 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry6);
  gtk_fixed_put (GTK_FIXED (fixed12), comboboxentry6, 200, 296);
  gtk_widget_set_size_request (comboboxentry6, 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("S'inscrire a un evenement"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("Solliciter entraineur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("S'inscrire a un cours sportifs"));

  label174 = gtk_label_new (_("<b>Mot de passe:</b>"));
  gtk_widget_show (label174);
  gtk_fixed_put (GTK_FIXED (fixed12), label174, 64, 208);
  gtk_widget_set_size_request (label174, 104, 32);
  gtk_label_set_use_markup (GTK_LABEL (label174), TRUE);

  label175 = gtk_label_new (_("<b>Identifiant:</b>"));
  gtk_widget_show (label175);
  gtk_fixed_put (GTK_FIXED (fixed12), label175, 72, 128);
  gtk_widget_set_size_request (label175, 96, 32);
  gtk_label_set_use_markup (GTK_LABEL (label175), TRUE);

  label176 = gtk_label_new (_("<span font=\"poppins bold 18\">Espace du membre</span>"));
  gtk_widget_show (label176);
  gtk_fixed_put (GTK_FIXED (fixed12), label176, 184, 24);
  gtk_widget_set_size_request (label176, 256, 40);
  gtk_label_set_use_markup (GTK_LABEL (label176), TRUE);

  button33 = gtk_button_new ();
  gtk_widget_show (button33);
  gtk_fixed_put (GTK_FIXED (fixed12), button33, 400, 440);
  gtk_widget_set_size_request (button33, 112, 32);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (button33), alignment29);

  hbox77 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox77);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox77);

  image28 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox77), image28, FALSE, FALSE, 0);

  label172 = gtk_label_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (label172);
  gtk_box_pack_start (GTK_BOX (hbox77), label172, FALSE, FALSE, 0);

  membre_acceuil = gtk_label_new (_("membre"));
  gtk_widget_show (membre_acceuil);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), membre_acceuil);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (page_d_acceuil, page_d_acceuil, "page_d_acceuil");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, entry36, "entry36");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, entry37, "entry37");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, button30, "button30");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, hbox74, "hbox74");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, image25, "image25");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, label166, "label166");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, button29, "button29");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, hbox73, "hbox73");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, image24, "image24");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, label165, "label165");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, comboboxentry4, "comboboxentry4");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, label163, "label163");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, label162, "label162");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, label164, "label164");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, admin_acceuil, "admin_acceuil");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, entry38, "entry38");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, entry39, "entry39");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, calendar2, "calendar2");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, button31, "button31");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, hbox75, "hbox75");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, image26, "image26");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, label167, "label167");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, button32, "button32");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, hbox76, "hbox76");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, image27, "image27");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, label168, "label168");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, comboboxentry5, "comboboxentry5");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, label169, "label169");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, label170, "label170");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, label171, "label171");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, entraineur_acceuil, "entraineur_acceuil");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, entry40, "entry40");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, entry41, "entry41");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, calendar3, "calendar3");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, button34, "button34");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, hbox78, "hbox78");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, image29, "image29");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, label173, "label173");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, comboboxentry6, "comboboxentry6");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, label174, "label174");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, label175, "label175");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, label176, "label176");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, button33, "button33");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, hbox77, "hbox77");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, image28, "image28");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, label172, "label172");
  GLADE_HOOKUP_OBJECT (page_d_acceuil, membre_acceuil, "membre_acceuil");

  return page_d_acceuil;
}

GtkWidget*
create_cour_sportif_acceuil (void)
{
  GtkWidget *cour_sportif_acceuil;
  GtkWidget *vbox1;
  GtkWidget *label1;
  GtkWidget *hbox1;
  GtkWidget *entry46;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox5;
  GtkWidget *image1;
  GtkWidget *label3;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;
  GtkWidget *hbox2;
  GtkWidget *button2;
  GtkWidget *alignment2;
  GtkWidget *hbox6;
  GtkWidget *image2;
  GtkWidget *label4;
  GtkWidget *button3;
  GtkWidget *alignment3;
  GtkWidget *hbox7;
  GtkWidget *image3;
  GtkWidget *label5;
  GtkWidget *button4;
  GtkWidget *alignment4;
  GtkWidget *hbox8;
  GtkWidget *image4;
  GtkWidget *label6;

  cour_sportif_acceuil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (cour_sportif_acceuil), _("cour_sportif_acceuil"));

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (cour_sportif_acceuil), vbox1);
  gtk_widget_set_size_request (vbox1, 700, 550);

  label1 = gtk_label_new (_("<span font = \"poppins bold 18 \">Gestion des cours sportifs</span>"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (vbox1), label1, FALSE, FALSE, 25);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  entry46 = gtk_entry_new ();
  gtk_widget_show (entry46);
  gtk_box_pack_start (GTK_BOX (hbox1), entry46, TRUE, TRUE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry46), 8226);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_box_pack_start (GTK_BOX (hbox1), button1, FALSE, FALSE, 0);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0.03, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox5);

  image1 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox5), image1, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("rechercher"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox5), label3, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (treeview1), FALSE);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox2, TRUE, TRUE, 0);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_box_pack_start (GTK_BOX (hbox2), button2, TRUE, TRUE, 5);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2), alignment2);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox6);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox6), image2, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox6), label4, FALSE, FALSE, 0);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_box_pack_start (GTK_BOX (hbox2), button3, TRUE, TRUE, 0);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3), alignment3);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox7);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox7), image3, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox7), label5, FALSE, FALSE, 0);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_box_pack_start (GTK_BOX (hbox2), button4, TRUE, TRUE, 5);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button4), alignment4);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox8);

  image4 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox8), image4, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox8), label6, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) cour_sportif_acceuil, "focus_in_event",
                    G_CALLBACK (on_cour_sportif_acceuil_focus_in_event),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (cour_sportif_acceuil, cour_sportif_acceuil, "cour_sportif_acceuil");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, label1, "label1");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, entry46, "entry46");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, button1, "button1");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, image1, "image1");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, label3, "label3");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, button2, "button2");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, image2, "image2");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, label4, "label4");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, button3, "button3");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, image3, "image3");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, label5, "label5");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, button4, "button4");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, image4, "image4");
  GLADE_HOOKUP_OBJECT (cour_sportif_acceuil, label6, "label6");

  return cour_sportif_acceuil;
}

GtkWidget*
create_ajouter_cour (void)
{
  GtkWidget *ajouter_cour;
  GtkWidget *vbox5;
  GtkWidget *label11;
  GtkWidget *hbox14;
  GtkWidget *label12;
  GtkWidget *hbox84;
  GtkWidget *entry42;
  GtkWidget *label180;
  GtkWidget *entry43;
  GtkWidget *hbox15;
  GtkWidget *label13;
  GtkWidget *hbox19;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkWidget *label14;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *hbox16;
  GtkWidget *label15;
  GtkWidget *comboboxentry7;
  GtkWidget *hbox17;
  GtkWidget *radiobutton2;
  GSList *radiobutton2_group = NULL;
  GtkWidget *radiobutton3;
  GtkWidget *hbox18;
  GtkWidget *label16;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *hbox101;
  GtkWidget *button46;
  GtkWidget *button47;

  ajouter_cour = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter_cour), _("ajouter_cour"));

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (ajouter_cour), vbox5);
  gtk_widget_set_size_request (vbox5, 700, 550);

  label11 = gtk_label_new (_("<span font = \"poppins bold 18\">Ajouter un cour</span>"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (vbox5), label11, TRUE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label11), 0.5, 0.46);

  hbox14 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox14);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox14, FALSE, FALSE, 0);

  label12 = gtk_label_new (_("<b>Nom du cour</b>"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox14), label12, FALSE, FALSE, 10);
  gtk_label_set_use_markup (GTK_LABEL (label12), TRUE);

  hbox84 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox84);
  gtk_box_pack_start (GTK_BOX (hbox14), hbox84, TRUE, TRUE, 10);

  entry42 = gtk_entry_new ();
  gtk_widget_show (entry42);
  gtk_box_pack_start (GTK_BOX (hbox84), entry42, TRUE, TRUE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry42), 8226);

  label180 = gtk_label_new (_("<b>Id cour</b>"));
  gtk_widget_show (label180);
  gtk_box_pack_start (GTK_BOX (hbox84), label180, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label180), TRUE);

  entry43 = gtk_entry_new ();
  gtk_widget_show (entry43);
  gtk_box_pack_start (GTK_BOX (hbox84), entry43, TRUE, TRUE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry43), 8226);

  hbox15 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox15);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox15, TRUE, TRUE, 0);

  label13 = gtk_label_new (_("<b>Date</b>"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox15), label13, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  hbox19 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox19);
  gtk_box_pack_start (GTK_BOX (hbox15), hbox19, TRUE, TRUE, 0);

  spinbutton3_adj = gtk_adjustment_new (1, 0, 31, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_box_pack_start (GTK_BOX (hbox19), spinbutton3, TRUE, TRUE, 0);

  spinbutton4_adj = gtk_adjustment_new (0, 0, 12, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_box_pack_start (GTK_BOX (hbox19), spinbutton4, TRUE, TRUE, 0);

  spinbutton5_adj = gtk_adjustment_new (1, 0, 3000, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_box_pack_start (GTK_BOX (hbox19), spinbutton5, TRUE, TRUE, 0);

  label14 = gtk_label_new (_("<b>Temps de depart</b>"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox15), label14, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);

  spinbutton1_adj = gtk_adjustment_new (8, 0, 24, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 0.5, 0);
  gtk_widget_show (spinbutton1);
  gtk_box_pack_start (GTK_BOX (hbox15), spinbutton1, TRUE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton1), TRUE);
  gtk_spin_button_set_snap_to_ticks (GTK_SPIN_BUTTON (spinbutton1), TRUE);

  hbox16 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox16);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox16, TRUE, TRUE, 0);

  label15 = gtk_label_new (_("<b>Type de cour</b>"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox16), label15, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  comboboxentry7 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry7);
  gtk_box_pack_start (GTK_BOX (hbox16), comboboxentry7, TRUE, TRUE, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("Yoga"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("Pilate"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("Musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("Hiit"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("spining"));

  hbox17 = gtk_hbox_new (FALSE, 0);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox17, TRUE, TRUE, 0);

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Mixte"));
  gtk_widget_show (radiobutton2);
  gtk_box_pack_start (GTK_BOX (hbox17), radiobutton2, TRUE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("Non mixte"));
  gtk_widget_show (radiobutton3);
  gtk_box_pack_start (GTK_BOX (hbox17), radiobutton3, TRUE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  hbox18 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox18);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox18, TRUE, TRUE, 0);

  label16 = gtk_label_new (_("<b>Nb de personne max</b>"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox18), label16, FALSE, FALSE, 10);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  spinbutton2_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_box_pack_start (GTK_BOX (hbox18), spinbutton2, TRUE, TRUE, 10);

  hbox101 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox101);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox101, FALSE, FALSE, 0);

  button46 = gtk_button_new_with_mnemonic (_("comfirmer"));
  gtk_widget_show (button46);
  gtk_box_pack_start (GTK_BOX (hbox101), button46, TRUE, FALSE, 0);

  button47 = gtk_button_new_with_mnemonic (_("annuler"));
  gtk_widget_show (button47);
  gtk_box_pack_start (GTK_BOX (hbox101), button47, TRUE, FALSE, 0);

  g_signal_connect ((gpointer) button46, "clicked",
                    G_CALLBACK (on_button46_clicked),
                    NULL);
  g_signal_connect ((gpointer) button47, "clicked",
                    G_CALLBACK (on_button47_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter_cour, ajouter_cour, "ajouter_cour");
  GLADE_HOOKUP_OBJECT (ajouter_cour, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (ajouter_cour, label11, "label11");
  GLADE_HOOKUP_OBJECT (ajouter_cour, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (ajouter_cour, label12, "label12");
  GLADE_HOOKUP_OBJECT (ajouter_cour, hbox84, "hbox84");
  GLADE_HOOKUP_OBJECT (ajouter_cour, entry42, "entry42");
  GLADE_HOOKUP_OBJECT (ajouter_cour, label180, "label180");
  GLADE_HOOKUP_OBJECT (ajouter_cour, entry43, "entry43");
  GLADE_HOOKUP_OBJECT (ajouter_cour, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (ajouter_cour, label13, "label13");
  GLADE_HOOKUP_OBJECT (ajouter_cour, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (ajouter_cour, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (ajouter_cour, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (ajouter_cour, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (ajouter_cour, label14, "label14");
  GLADE_HOOKUP_OBJECT (ajouter_cour, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (ajouter_cour, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (ajouter_cour, label15, "label15");
  GLADE_HOOKUP_OBJECT (ajouter_cour, comboboxentry7, "comboboxentry7");
  GLADE_HOOKUP_OBJECT (ajouter_cour, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (ajouter_cour, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (ajouter_cour, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (ajouter_cour, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (ajouter_cour, label16, "label16");
  GLADE_HOOKUP_OBJECT (ajouter_cour, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (ajouter_cour, hbox101, "hbox101");
  GLADE_HOOKUP_OBJECT (ajouter_cour, button46, "button46");
  GLADE_HOOKUP_OBJECT (ajouter_cour, button47, "button47");

  return ajouter_cour;
}

GtkWidget*
create_modifer_cour (void)
{
  GtkWidget *modifer_cour;
  GtkWidget *vbox46;
  GtkWidget *label181;
  GtkWidget *hbox85;
  GtkWidget *label182;
  GtkWidget *hbox86;
  GtkWidget *entry44;
  GtkWidget *label183;
  GtkWidget *entry45;
  GtkWidget *hbox87;
  GtkWidget *label184;
  GtkWidget *hbox88;
  GtkObject *spinbutton19_adj;
  GtkWidget *spinbutton19;
  GtkObject *spinbutton20_adj;
  GtkWidget *spinbutton20;
  GtkObject *spinbutton21_adj;
  GtkWidget *spinbutton21;
  GtkWidget *label185;
  GtkObject *spinbutton22_adj;
  GtkWidget *spinbutton22;
  GtkWidget *hbox89;
  GtkWidget *label186;
  GtkWidget *comboboxentry8;
  GtkWidget *hbox90;
  GtkWidget *radiobutton8;
  GSList *radiobutton8_group = NULL;
  GtkWidget *radiobutton9;
  GSList *radiobutton9_group = NULL;
  GtkWidget *hbox91;
  GtkWidget *label187;
  GtkObject *spinbutton23_adj;
  GtkWidget *spinbutton23;
  GtkWidget *hbox102;
  GtkWidget *button49;
  GtkWidget *button50;

  modifer_cour = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifer_cour), _("modifier_cour"));

  vbox46 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox46);
  gtk_container_add (GTK_CONTAINER (modifer_cour), vbox46);
  gtk_widget_set_size_request (vbox46, 700, 550);

  label181 = gtk_label_new (_("<span font=\"poppins bold 18\">Modifier un cour</span>"));
  gtk_widget_show (label181);
  gtk_box_pack_start (GTK_BOX (vbox46), label181, TRUE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label181), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label181), 0.5, 0.46);

  hbox85 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox85);
  gtk_box_pack_start (GTK_BOX (vbox46), hbox85, FALSE, FALSE, 0);

  label182 = gtk_label_new (_("<b>Nom du cour</b>"));
  gtk_widget_show (label182);
  gtk_box_pack_start (GTK_BOX (hbox85), label182, FALSE, FALSE, 10);
  gtk_label_set_use_markup (GTK_LABEL (label182), TRUE);

  hbox86 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox86);
  gtk_box_pack_start (GTK_BOX (hbox85), hbox86, TRUE, TRUE, 10);

  entry44 = gtk_entry_new ();
  gtk_widget_show (entry44);
  gtk_box_pack_start (GTK_BOX (hbox86), entry44, TRUE, TRUE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry44), 8226);

  label183 = gtk_label_new (_("<b>Id cour</b>"));
  gtk_widget_show (label183);
  gtk_box_pack_start (GTK_BOX (hbox86), label183, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label183), TRUE);

  entry45 = gtk_entry_new ();
  gtk_widget_show (entry45);
  gtk_box_pack_start (GTK_BOX (hbox86), entry45, TRUE, TRUE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry45), 8226);

  hbox87 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox87);
  gtk_box_pack_start (GTK_BOX (vbox46), hbox87, TRUE, TRUE, 0);

  label184 = gtk_label_new (_("<b>Date</b>"));
  gtk_widget_show (label184);
  gtk_box_pack_start (GTK_BOX (hbox87), label184, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label184), TRUE);

  hbox88 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox88);
  gtk_box_pack_start (GTK_BOX (hbox87), hbox88, TRUE, TRUE, 0);

  spinbutton19_adj = gtk_adjustment_new (1, 0, 31, 1, 10, 10);
  spinbutton19 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton19_adj), 1, 0);
  gtk_widget_show (spinbutton19);
  gtk_box_pack_start (GTK_BOX (hbox88), spinbutton19, TRUE, TRUE, 0);

  spinbutton20_adj = gtk_adjustment_new (0, 0, 12, 1, 10, 10);
  spinbutton20 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton20_adj), 1, 0);
  gtk_widget_show (spinbutton20);
  gtk_box_pack_start (GTK_BOX (hbox88), spinbutton20, TRUE, TRUE, 0);

  spinbutton21_adj = gtk_adjustment_new (1, 0, 3000, 1, 10, 10);
  spinbutton21 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton21_adj), 1, 0);
  gtk_widget_show (spinbutton21);
  gtk_box_pack_start (GTK_BOX (hbox88), spinbutton21, TRUE, TRUE, 0);

  label185 = gtk_label_new (_("<b>Temps de depart</b>"));
  gtk_widget_show (label185);
  gtk_box_pack_start (GTK_BOX (hbox87), label185, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label185), TRUE);

  spinbutton22_adj = gtk_adjustment_new (1, 0, 24, 1, 10, 10);
  spinbutton22 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton22_adj), 1, 0);
  gtk_widget_show (spinbutton22);
  gtk_box_pack_start (GTK_BOX (hbox87), spinbutton22, TRUE, TRUE, 0);
  gtk_spin_button_set_snap_to_ticks (GTK_SPIN_BUTTON (spinbutton22), TRUE);

  hbox89 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox89);
  gtk_box_pack_start (GTK_BOX (vbox46), hbox89, TRUE, TRUE, 0);

  label186 = gtk_label_new (_("<b>Type de cour</b>"));
  gtk_widget_show (label186);
  gtk_box_pack_start (GTK_BOX (hbox89), label186, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label186), TRUE);

  comboboxentry8 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry8);
  gtk_box_pack_start (GTK_BOX (hbox89), comboboxentry8, TRUE, TRUE, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("Yoga"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("Pilate"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("Musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("Hiit"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("spining"));

  hbox90 = gtk_hbox_new (FALSE, 0);
  gtk_box_pack_start (GTK_BOX (vbox46), hbox90, TRUE, TRUE, 0);

  radiobutton8 = gtk_radio_button_new_with_mnemonic (NULL, _("Mixte"));
  gtk_widget_show (radiobutton8);
  gtk_box_pack_start (GTK_BOX (hbox90), radiobutton8, TRUE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton8), radiobutton8_group);
  radiobutton8_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton8));

  radiobutton9 = gtk_radio_button_new_with_mnemonic (NULL, _("Non mixte"));
  gtk_widget_show (radiobutton9);
  gtk_box_pack_start (GTK_BOX (hbox90), radiobutton9, TRUE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton9), radiobutton9_group);
  radiobutton9_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton9));

  hbox91 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox91);
  gtk_box_pack_start (GTK_BOX (vbox46), hbox91, TRUE, TRUE, 0);

  label187 = gtk_label_new (_("<b>Nb de personne max</b>"));
  gtk_widget_show (label187);
  gtk_box_pack_start (GTK_BOX (hbox91), label187, FALSE, FALSE, 10);
  gtk_label_set_use_markup (GTK_LABEL (label187), TRUE);

  spinbutton23_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton23 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton23_adj), 1, 0);
  gtk_widget_show (spinbutton23);
  gtk_box_pack_start (GTK_BOX (hbox91), spinbutton23, TRUE, TRUE, 10);

  hbox102 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox102);
  gtk_box_pack_start (GTK_BOX (vbox46), hbox102, FALSE, FALSE, 0);

  button49 = gtk_button_new_with_mnemonic (_("comfirmer"));
  gtk_widget_show (button49);
  gtk_box_pack_start (GTK_BOX (hbox102), button49, TRUE, FALSE, 0);

  button50 = gtk_button_new_with_mnemonic (_("annuler"));
  gtk_widget_show (button50);
  gtk_box_pack_start (GTK_BOX (hbox102), button50, TRUE, FALSE, 0);

  g_signal_connect ((gpointer) button49, "clicked",
                    G_CALLBACK (on_button49_clicked),
                    NULL);
  g_signal_connect ((gpointer) button50, "clicked",
                    G_CALLBACK (on_button50_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifer_cour, modifer_cour, "modifer_cour");
  GLADE_HOOKUP_OBJECT (modifer_cour, vbox46, "vbox46");
  GLADE_HOOKUP_OBJECT (modifer_cour, label181, "label181");
  GLADE_HOOKUP_OBJECT (modifer_cour, hbox85, "hbox85");
  GLADE_HOOKUP_OBJECT (modifer_cour, label182, "label182");
  GLADE_HOOKUP_OBJECT (modifer_cour, hbox86, "hbox86");
  GLADE_HOOKUP_OBJECT (modifer_cour, entry44, "entry44");
  GLADE_HOOKUP_OBJECT (modifer_cour, label183, "label183");
  GLADE_HOOKUP_OBJECT (modifer_cour, entry45, "entry45");
  GLADE_HOOKUP_OBJECT (modifer_cour, hbox87, "hbox87");
  GLADE_HOOKUP_OBJECT (modifer_cour, label184, "label184");
  GLADE_HOOKUP_OBJECT (modifer_cour, hbox88, "hbox88");
  GLADE_HOOKUP_OBJECT (modifer_cour, spinbutton19, "spinbutton19");
  GLADE_HOOKUP_OBJECT (modifer_cour, spinbutton20, "spinbutton20");
  GLADE_HOOKUP_OBJECT (modifer_cour, spinbutton21, "spinbutton21");
  GLADE_HOOKUP_OBJECT (modifer_cour, label185, "label185");
  GLADE_HOOKUP_OBJECT (modifer_cour, spinbutton22, "spinbutton22");
  GLADE_HOOKUP_OBJECT (modifer_cour, hbox89, "hbox89");
  GLADE_HOOKUP_OBJECT (modifer_cour, label186, "label186");
  GLADE_HOOKUP_OBJECT (modifer_cour, comboboxentry8, "comboboxentry8");
  GLADE_HOOKUP_OBJECT (modifer_cour, hbox90, "hbox90");
  GLADE_HOOKUP_OBJECT (modifer_cour, radiobutton8, "radiobutton8");
  GLADE_HOOKUP_OBJECT (modifer_cour, radiobutton9, "radiobutton9");
  GLADE_HOOKUP_OBJECT (modifer_cour, hbox91, "hbox91");
  GLADE_HOOKUP_OBJECT (modifer_cour, label187, "label187");
  GLADE_HOOKUP_OBJECT (modifer_cour, spinbutton23, "spinbutton23");
  GLADE_HOOKUP_OBJECT (modifer_cour, hbox102, "hbox102");
  GLADE_HOOKUP_OBJECT (modifer_cour, button49, "button49");
  GLADE_HOOKUP_OBJECT (modifer_cour, button50, "button50");

  return modifer_cour;
}

GtkWidget*
create_inscrit_cour (void)
{
  GtkWidget *inscrit_cour;
  GtkWidget *fixed13;
  GtkWidget *entry47;
  GtkWidget *entry48;
  GtkWidget *radiobutton10;
  GSList *radiobutton10_group = NULL;
  GtkWidget *radiobutton11;
  GtkWidget *radiobutton12;
  GtkWidget *label200;
  GtkWidget *comboboxentry9;
  GtkWidget *label199;
  GtkWidget *label198;
  GtkWidget *checkbutton1;
  GtkWidget *button52;
  GtkWidget *button51;

  inscrit_cour = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (inscrit_cour), _("inscription a un cour"));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (inscrit_cour), fixed13);
  gtk_widget_set_size_request (fixed13, 700, 550);

  entry47 = gtk_entry_new ();
  gtk_widget_show (entry47);
  gtk_fixed_put (GTK_FIXED (fixed13), entry47, 232, 64);
  gtk_widget_set_size_request (entry47, 232, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry47), 8226);

  entry48 = gtk_entry_new ();
  gtk_widget_show (entry48);
  gtk_fixed_put (GTK_FIXED (fixed13), entry48, 232, 144);
  gtk_widget_set_size_request (entry48, 232, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry48), 8226);

  radiobutton10 = gtk_radio_button_new_with_mnemonic (NULL, _("debutant"));
  gtk_widget_show (radiobutton10);
  gtk_fixed_put (GTK_FIXED (fixed13), radiobutton10, 48, 304);
  gtk_widget_set_size_request (radiobutton10, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton10), radiobutton10_group);
  radiobutton10_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton10));

  radiobutton11 = gtk_radio_button_new_with_mnemonic (NULL, _("intermediaire"));
  gtk_widget_show (radiobutton11);
  gtk_fixed_put (GTK_FIXED (fixed13), radiobutton11, 280, 304);
  gtk_widget_set_size_request (radiobutton11, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton11), radiobutton10_group);
  radiobutton10_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton11));

  radiobutton12 = gtk_radio_button_new_with_mnemonic (NULL, _("expert"));
  gtk_widget_show (radiobutton12);
  gtk_fixed_put (GTK_FIXED (fixed13), radiobutton12, 528, 304);
  gtk_widget_set_size_request (radiobutton12, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton12), radiobutton10_group);
  radiobutton10_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton12));

  label200 = gtk_label_new (_("<span font=\"poppins bold 18\">S'inscrire a un cour</span>"));
  gtk_widget_show (label200);
  gtk_fixed_put (GTK_FIXED (fixed13), label200, 224, 16);
  gtk_widget_set_size_request (label200, 288, 32);
  gtk_label_set_use_markup (GTK_LABEL (label200), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label200), 0.5, 0.46);

  comboboxentry9 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry9);
  gtk_fixed_put (GTK_FIXED (fixed13), comboboxentry9, 144, 224);
  gtk_widget_set_size_request (comboboxentry9, 389, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry9), _("yoga"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry9), _("spinning"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry9), _("box"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry9), _("musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry9), _("hiit"));

  label199 = gtk_label_new (_("<b>prenom</b>"));
  gtk_widget_show (label199);
  gtk_fixed_put (GTK_FIXED (fixed13), label199, 72, 144);
  gtk_widget_set_size_request (label199, 80, 32);
  gtk_label_set_use_markup (GTK_LABEL (label199), TRUE);

  label198 = gtk_label_new (_("<b>nom</b>"));
  gtk_widget_show (label198);
  gtk_fixed_put (GTK_FIXED (fixed13), label198, 72, 64);
  gtk_widget_set_size_request (label198, 72, 24);
  gtk_label_set_use_markup (GTK_LABEL (label198), TRUE);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("M\342\200\231inscrire automatiquement la semaine prochaine"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed13), checkbutton1, 80, 376);
  gtk_widget_set_size_request (checkbutton1, 376, 24);

  button52 = gtk_button_new_with_mnemonic (_("annuler"));
  gtk_widget_show (button52);
  gtk_fixed_put (GTK_FIXED (fixed13), button52, 504, 464);
  gtk_widget_set_size_request (button52, 74, 29);

  button51 = gtk_button_new_with_mnemonic (_("s'inscrire"));
  gtk_widget_show (button51);
  gtk_fixed_put (GTK_FIXED (fixed13), button51, 120, 464);
  gtk_widget_set_size_request (button51, 74, 29);

  g_signal_connect ((gpointer) button52, "clicked",
                    G_CALLBACK (on_button52_clicked),
                    NULL);
  g_signal_connect ((gpointer) button51, "clicked",
                    G_CALLBACK (on_button51_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (inscrit_cour, inscrit_cour, "inscrit_cour");
  GLADE_HOOKUP_OBJECT (inscrit_cour, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (inscrit_cour, entry47, "entry47");
  GLADE_HOOKUP_OBJECT (inscrit_cour, entry48, "entry48");
  GLADE_HOOKUP_OBJECT (inscrit_cour, radiobutton10, "radiobutton10");
  GLADE_HOOKUP_OBJECT (inscrit_cour, radiobutton11, "radiobutton11");
  GLADE_HOOKUP_OBJECT (inscrit_cour, radiobutton12, "radiobutton12");
  GLADE_HOOKUP_OBJECT (inscrit_cour, label200, "label200");
  GLADE_HOOKUP_OBJECT (inscrit_cour, comboboxentry9, "comboboxentry9");
  GLADE_HOOKUP_OBJECT (inscrit_cour, label199, "label199");
  GLADE_HOOKUP_OBJECT (inscrit_cour, label198, "label198");
  GLADE_HOOKUP_OBJECT (inscrit_cour, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (inscrit_cour, button52, "button52");
  GLADE_HOOKUP_OBJECT (inscrit_cour, button51, "button51");

  return inscrit_cour;
}

