/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_page_d_acceuil (void);
GtkWidget* create_cour_sportif_acceuil (void);
GtkWidget* create_ajouter_cour (void);
GtkWidget* create_modifer_cour (void);
GtkWidget* create_inscrit_cour (void);
