/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_page_d_acceuil_GE (void)
{
  GtkWidget *page_d_acceuil_GE;
  GtkWidget *fixed1;
  GtkWidget *label1;
  GtkWidget *entry1;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label2;
  GtkWidget *treeview1;
  GtkWidget *button2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label3;
  GtkWidget *button4;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label5;
  GtkWidget *button3;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label4;

  page_d_acceuil_GE = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (page_d_acceuil_GE), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (page_d_acceuil_GE), fixed1);

  label1 = gtk_label_new (_("Gestion des entraineurs\n"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 32, 8);
  gtk_widget_set_size_request (label1, 312, 40);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 8, 40);
  gtk_widget_set_size_request (entry1, 248, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 264, 40);
  gtk_widget_set_size_request (button1, 128, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox1), label2, FALSE, FALSE, 0);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed1), treeview1, 0, 96);
  gtk_widget_set_size_request (treeview1, 344, 136);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (treeview1), FALSE);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 8, 272);
  gtk_widget_set_size_request (button2, 104, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, FALSE, FALSE, 0);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed1), button4, 296, 272);
  gtk_widget_set_size_request (button4, 104, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button4), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed1), button3, 136, 272);
  gtk_widget_set_size_request (button3, 120, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (page_d_acceuil_GE, page_d_acceuil_GE, "page_d_acceuil_GE");
  GLADE_HOOKUP_OBJECT (page_d_acceuil_GE, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (page_d_acceuil_GE, label1, "label1");
  GLADE_HOOKUP_OBJECT (page_d_acceuil_GE, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (page_d_acceuil_GE, button1, "button1");
  GLADE_HOOKUP_OBJECT (page_d_acceuil_GE, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (page_d_acceuil_GE, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (page_d_acceuil_GE, image1, "image1");
  GLADE_HOOKUP_OBJECT (page_d_acceuil_GE, label2, "label2");
  GLADE_HOOKUP_OBJECT (page_d_acceuil_GE, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (page_d_acceuil_GE, button2, "button2");
  GLADE_HOOKUP_OBJECT (page_d_acceuil_GE, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (page_d_acceuil_GE, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (page_d_acceuil_GE, image2, "image2");
  GLADE_HOOKUP_OBJECT (page_d_acceuil_GE, label3, "label3");
  GLADE_HOOKUP_OBJECT (page_d_acceuil_GE, button4, "button4");
  GLADE_HOOKUP_OBJECT (page_d_acceuil_GE, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (page_d_acceuil_GE, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (page_d_acceuil_GE, image4, "image4");
  GLADE_HOOKUP_OBJECT (page_d_acceuil_GE, label5, "label5");
  GLADE_HOOKUP_OBJECT (page_d_acceuil_GE, button3, "button3");
  GLADE_HOOKUP_OBJECT (page_d_acceuil_GE, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (page_d_acceuil_GE, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (page_d_acceuil_GE, image3, "image3");
  GLADE_HOOKUP_OBJECT (page_d_acceuil_GE, label4, "label4");

  return page_d_acceuil_GE;
}

