/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "trainer_callbacks.h"
#include "trainer_interface.h"
#include "../common/support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ajout_ (void)
{
  GtkWidget *ajout_;
  GtkWidget *fixed1;
  GtkWidget *labela1;
  GtkWidget *buttona1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *labela2;
  GtkWidget *buttona2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *labela3;

  ajout_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajout_), _("ajout?"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (ajout_), fixed1);
  gtk_widget_set_size_request (fixed1, 496, 168);

  labela1 = gtk_label_new (_("<span foreground=\"red\" weight=\"bold\">Voulez vous ajouter cet entraineur?</span>"));
  gtk_widget_show (labela1);
  gtk_fixed_put (GTK_FIXED (fixed1), labela1, 0, 24);
  gtk_widget_set_size_request (labela1, 496, 104);
  gtk_label_set_use_markup (GTK_LABEL (labela1), TRUE);
  gtk_misc_set_padding (GTK_MISC (labela1), 0, 4);

  buttona1 = gtk_button_new ();
  gtk_widget_show (buttona1);
  gtk_fixed_put (GTK_FIXED (fixed1), buttona1, 280, 136);
  gtk_widget_set_size_request (buttona1, 136, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttona1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  labela2 = gtk_label_new_with_mnemonic (_("<b>NON</b>"));
  gtk_widget_show (labela2);
  gtk_box_pack_start (GTK_BOX (hbox1), labela2, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (labela2), TRUE);

  buttona2 = gtk_button_new ();
  gtk_widget_show (buttona2);
  gtk_fixed_put (GTK_FIXED (fixed1), buttona2, 88, 136);
  gtk_widget_set_size_request (buttona2, 136, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttona2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  labela3 = gtk_label_new_with_mnemonic (_("<b>OUI</b>"));
  gtk_widget_show (labela3);
  gtk_box_pack_start (GTK_BOX (hbox2), labela3, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (labela3), TRUE);

  g_signal_connect ((gpointer) buttona1, "clicked",
                    G_CALLBACK (on_buttona1_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttona2, "clicked",
                    G_CALLBACK (on_buttona2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_, ajout_, "ajout_");
  GLADE_HOOKUP_OBJECT (ajout_, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (ajout_, labela1, "labela1");
  GLADE_HOOKUP_OBJECT (ajout_, buttona1, "buttona1");
  GLADE_HOOKUP_OBJECT (ajout_, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (ajout_, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (ajout_, image1, "image1");
  GLADE_HOOKUP_OBJECT (ajout_, labela2, "labela2");
  GLADE_HOOKUP_OBJECT (ajout_, buttona2, "buttona2");
  GLADE_HOOKUP_OBJECT (ajout_, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (ajout_, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (ajout_, image2, "image2");
  GLADE_HOOKUP_OBJECT (ajout_, labela3, "labela3");

  return ajout_;
}

GtkWidget*
create_modif_ (void)
{
  GtkWidget *modif_;
  GtkWidget *fixed2;
  GtkWidget *fixed3;
  GtkWidget *buttonm1;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *labelm2;
  GtkWidget *buttonm2;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *labelm3;
  GtkWidget *labelm1;

  modif_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modif_), _("modif?"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (modif_), fixed2);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_fixed_put (GTK_FIXED (fixed2), fixed3, 0, 0);
  gtk_widget_set_size_request (fixed3, 496, 224);

  buttonm1 = gtk_button_new ();
  gtk_widget_show (buttonm1);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonm1, 272, 152);
  gtk_widget_set_size_request (buttonm1, 136, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonm1), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  labelm2 = gtk_label_new_with_mnemonic (_("NON"));
  gtk_widget_show (labelm2);
  gtk_box_pack_start (GTK_BOX (hbox3), labelm2, FALSE, FALSE, 0);

  buttonm2 = gtk_button_new ();
  gtk_widget_show (buttonm2);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonm2, 88, 152);
  gtk_widget_set_size_request (buttonm2, 136, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonm2), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  labelm3 = gtk_label_new_with_mnemonic (_("OUI"));
  gtk_widget_show (labelm3);
  gtk_box_pack_start (GTK_BOX (hbox4), labelm3, FALSE, FALSE, 0);

  labelm1 = gtk_label_new (_("<span foreground=\"red\" weight=\"bold\">Voulez vous modifier cet entraineur?</span>"));
  gtk_widget_show (labelm1);
  gtk_fixed_put (GTK_FIXED (fixed3), labelm1, 0, 0);
  gtk_widget_set_size_request (labelm1, 440, 96);
  gtk_label_set_use_markup (GTK_LABEL (labelm1), TRUE);

  g_signal_connect ((gpointer) buttonm1, "clicked",
                    G_CALLBACK (on_buttonm1_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonm2, "clicked",
                    G_CALLBACK (on_buttonm2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modif_, modif_, "modif_");
  GLADE_HOOKUP_OBJECT (modif_, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (modif_, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (modif_, buttonm1, "buttonm1");
  GLADE_HOOKUP_OBJECT (modif_, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (modif_, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (modif_, image3, "image3");
  GLADE_HOOKUP_OBJECT (modif_, labelm2, "labelm2");
  GLADE_HOOKUP_OBJECT (modif_, buttonm2, "buttonm2");
  GLADE_HOOKUP_OBJECT (modif_, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (modif_, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (modif_, image4, "image4");
  GLADE_HOOKUP_OBJECT (modif_, labelm3, "labelm3");
  GLADE_HOOKUP_OBJECT (modif_, labelm1, "labelm1");

  return modif_;
}

GtkWidget*
create_inscri_ (void)
{
  GtkWidget *inscri_;
  GtkWidget *fixed4;
  GtkWidget *fixed5;
  GtkWidget *buttonI2;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *labelI3;
  GtkWidget *buttonI1;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *labelI2;
  GtkWidget *labelI1;

  inscri_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (inscri_), _("inscri?"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (inscri_), fixed4);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_fixed_put (GTK_FIXED (fixed4), fixed5, 0, 0);
  gtk_widget_set_size_request (fixed5, 480, 232);

  buttonI2 = gtk_button_new ();
  gtk_widget_show (buttonI2);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonI2, 72, 128);
  gtk_widget_set_size_request (buttonI2, 136, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttonI2), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  labelI3 = gtk_label_new_with_mnemonic (_("<b>OUI</b>"));
  gtk_widget_show (labelI3);
  gtk_box_pack_start (GTK_BOX (hbox6), labelI3, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (labelI3), TRUE);

  buttonI1 = gtk_button_new ();
  gtk_widget_show (buttonI1);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonI1, 256, 128);
  gtk_widget_set_size_request (buttonI1, 136, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (buttonI1), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  labelI2 = gtk_label_new_with_mnemonic (_("<b>NON</b>"));
  gtk_widget_show (labelI2);
  gtk_box_pack_start (GTK_BOX (hbox5), labelI2, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (labelI2), TRUE);

  labelI1 = gtk_label_new (_("<span foreground=\"red\" weight=\"bold\">Voulez vous vraiment s'inscrire?</span>"));
  gtk_widget_show (labelI1);
  gtk_fixed_put (GTK_FIXED (fixed5), labelI1, 0, 0);
  gtk_widget_set_size_request (labelI1, 432, 88);
  gtk_label_set_use_markup (GTK_LABEL (labelI1), TRUE);

  g_signal_connect ((gpointer) buttonI1, "clicked",
                    G_CALLBACK (on_buttonI1_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonI2, "clicked",
                    G_CALLBACK (on_buttonI2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (inscri_, inscri_, "inscri_");
  GLADE_HOOKUP_OBJECT (inscri_, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (inscri_, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (inscri_, buttonI2, "buttonI2");
  GLADE_HOOKUP_OBJECT (inscri_, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (inscri_, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (inscri_, image6, "image6");
  GLADE_HOOKUP_OBJECT (inscri_, labelI3, "labelI3");
  GLADE_HOOKUP_OBJECT (inscri_, buttonI1, "buttonI1");
  GLADE_HOOKUP_OBJECT (inscri_, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (inscri_, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (inscri_, image5, "image5");
  GLADE_HOOKUP_OBJECT (inscri_, labelI2, "labelI2");
  GLADE_HOOKUP_OBJECT (inscri_, labelI1, "labelI1");

  return inscri_;
}

GtkWidget*
create_supp_ (void)
{
  GtkWidget *supp_;
  GtkWidget *fixed6;
  GtkWidget *fixed7;
  GtkWidget *labels1;
  GtkWidget *buttons1;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *labels2;
  GtkWidget *buttons2;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *labels3;

  supp_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supp_), _("supp?"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (supp_), fixed6);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_fixed_put (GTK_FIXED (fixed6), fixed7, 0, 0);
  gtk_widget_set_size_request (fixed7, 480, 232);

  labels1 = gtk_label_new (_("<span foreground=\"red\" weight=\"bold\">Voulez vous vraiment suppeimer cet entraineur?</span>"));
  gtk_widget_show (labels1);
  gtk_fixed_put (GTK_FIXED (fixed7), labels1, 0, 40);
  gtk_widget_set_size_request (labels1, 432, 88);
  gtk_label_set_use_markup (GTK_LABEL (labels1), TRUE);

  buttons1 = gtk_button_new ();
  gtk_widget_show (buttons1);
  gtk_fixed_put (GTK_FIXED (fixed7), buttons1, 256, 128);
  gtk_widget_set_size_request (buttons1, 136, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttons1), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  labels2 = gtk_label_new_with_mnemonic (_("<b>NON</b>"));
  gtk_widget_show (labels2);
  gtk_box_pack_start (GTK_BOX (hbox8), labels2, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (labels2), TRUE);

  buttons2 = gtk_button_new ();
  gtk_widget_show (buttons2);
  gtk_fixed_put (GTK_FIXED (fixed7), buttons2, 72, 128);
  gtk_widget_set_size_request (buttons2, 136, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttons2), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  labels3 = gtk_label_new_with_mnemonic (_("<b>OUI</b>"));
  gtk_widget_show (labels3);
  gtk_box_pack_start (GTK_BOX (hbox7), labels3, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (labels3), TRUE);

  g_signal_connect ((gpointer) buttons1, "clicked",
                    G_CALLBACK (on_buttons1_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttons2, "clicked",
                    G_CALLBACK (on_buttons2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supp_, supp_, "supp_");
  GLADE_HOOKUP_OBJECT (supp_, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (supp_, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (supp_, labels1, "labels1");
  GLADE_HOOKUP_OBJECT (supp_, buttons1, "buttons1");
  GLADE_HOOKUP_OBJECT (supp_, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (supp_, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (supp_, image8, "image8");
  GLADE_HOOKUP_OBJECT (supp_, labels2, "labels2");
  GLADE_HOOKUP_OBJECT (supp_, buttons2, "buttons2");
  GLADE_HOOKUP_OBJECT (supp_, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (supp_, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (supp_, image7, "image7");
  GLADE_HOOKUP_OBJECT (supp_, labels3, "labels3");

  return supp_;
}

GtkWidget*
create_Gestion_des_entraineur (void)
{
  GtkWidget *Gestion_des_entraineur;
  GtkWidget *fixed8;
  GtkWidget *entryG1;
  GtkWidget *treeview1;
  GtkWidget *buttonG5;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *labelG6;
  GtkWidget *labelG1;
  GtkWidget *labelG7;
  GtkWidget *buttonG4;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *labelG5;
  GtkWidget *buttonG3;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *labelG4;
  GtkWidget *buttonG1;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *imageG1;
  GtkWidget *labelG2;
  GtkWidget *buttonG2;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *labelG3;

  Gestion_des_entraineur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Gestion_des_entraineur), _("Gestion_des_entraineur"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (Gestion_des_entraineur), fixed8);

  entryG1 = gtk_entry_new ();
  gtk_widget_show (entryG1);
  gtk_fixed_put (GTK_FIXED (fixed8), entryG1, 104, 96);
  gtk_widget_set_size_request (entryG1, 376, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryG1), 8226);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed8), treeview1, 40, 168);
  gtk_widget_set_size_request (treeview1, 600, 232);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (treeview1), FALSE);

  buttonG5 = gtk_button_new ();
  gtk_widget_show (buttonG5);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonG5, 0, 8);
  gtk_widget_set_size_request (buttonG5, 112, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (buttonG5), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  labelG6 = gtk_label_new_with_mnemonic (_("<b>Pr\303\251c\303\251dent</b>"));
  gtk_widget_show (labelG6);
  gtk_box_pack_start (GTK_BOX (hbox12), labelG6, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (labelG6), TRUE);

  labelG1 = gtk_label_new (_("<span font=\"Poppins Bold 18\">Gestion des entraineurs</span>\n\n"));
  gtk_widget_show (labelG1);
  gtk_fixed_put (GTK_FIXED (fixed8), labelG1, 136, 16);
  gtk_widget_set_size_request (labelG1, 320, 96);
  gtk_label_set_use_markup (GTK_LABEL (labelG1), TRUE);

  labelG7 = gtk_label_new (_("<b>CIN</b>"));
  gtk_widget_show (labelG7);
  gtk_fixed_put (GTK_FIXED (fixed8), labelG7, 32, 96);
  gtk_widget_set_size_request (labelG7, 88, 42);
  gtk_label_set_use_markup (GTK_LABEL (labelG7), TRUE);

  buttonG4 = gtk_button_new ();
  gtk_widget_show (buttonG4);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonG4, 64, 432);
  gtk_widget_set_size_request (buttonG4, 128, 48);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (buttonG4), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  labelG5 = gtk_label_new_with_mnemonic (_("<b>Ajouter</b>"));
  gtk_widget_show (labelG5);
  gtk_box_pack_start (GTK_BOX (hbox13), labelG5, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (labelG5), TRUE);

  buttonG3 = gtk_button_new ();
  gtk_widget_show (buttonG3);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonG3, 296, 432);
  gtk_widget_set_size_request (buttonG3, 120, 48);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (buttonG3), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  labelG4 = gtk_label_new_with_mnemonic (_("<b>Modifier</b>"));
  gtk_widget_show (labelG4);
  gtk_box_pack_start (GTK_BOX (hbox9), labelG4, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (labelG4), TRUE);

  buttonG1 = gtk_button_new ();
  gtk_widget_show (buttonG1);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonG1, 488, 96);
  gtk_widget_set_size_request (buttonG1, 152, 48);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (buttonG1), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  imageG1 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (imageG1);
  gtk_box_pack_start (GTK_BOX (hbox11), imageG1, FALSE, FALSE, 0);

  labelG2 = gtk_label_new_with_mnemonic (_("<b>Rechercher</b>"));
  gtk_widget_show (labelG2);
  gtk_box_pack_start (GTK_BOX (hbox11), labelG2, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (labelG2), TRUE);

  buttonG2 = gtk_button_new ();
  gtk_widget_show (buttonG2);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonG2, 528, 432);
  gtk_widget_set_size_request (buttonG2, 112, 48);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (buttonG2), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  labelG3 = gtk_label_new_with_mnemonic (_("<b>Supprimer</b>"));
  gtk_widget_show (labelG3);
  gtk_box_pack_start (GTK_BOX (hbox10), labelG3, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (labelG3), TRUE);

  g_signal_connect ((gpointer) buttonG4, "clicked",
                    G_CALLBACK (on_buttonG4_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonG3, "clicked",
                    G_CALLBACK (on_buttonG3_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonG1, "clicked",
                    G_CALLBACK (on_buttonG1_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonG2, "clicked",
                    G_CALLBACK (on_buttonG2_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonG5, "clicked",
                    G_CALLBACK (on_buttonG5_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_des_entraineur, Gestion_des_entraineur, "Gestion_des_entraineur");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, entryG1, "entryG1");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, buttonG5, "buttonG5");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, image12, "image12");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, labelG6, "labelG6");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, labelG1, "labelG1");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, labelG7, "labelG7");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, buttonG4, "buttonG4");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, image13, "image13");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, labelG5, "labelG5");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, buttonG3, "buttonG3");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, image9, "image9");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, labelG4, "labelG4");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, buttonG1, "buttonG1");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, imageG1, "imageG1");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, labelG2, "labelG2");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, buttonG2, "buttonG2");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, image10, "image10");
  GLADE_HOOKUP_OBJECT (Gestion_des_entraineur, labelG3, "labelG3");

  return Gestion_des_entraineur;
}

GtkWidget*
create_Ajouter_un_entraineur (void)
{
  GtkWidget *Ajouter_un_entraineur;
  GtkWidget *fixed9;
  GtkWidget *entryA1;
  GtkWidget *entryA2;
  GtkWidget *entryA4;
  GtkWidget *entryA5;
  GtkWidget *entryA6;
  GtkWidget *calendar1A;
  GtkWidget *entryA3;
  GtkObject *spinbutton1A_adj;
  GtkWidget *spinbutton1A;
  GtkObject *spinbutton2A_adj;
  GtkWidget *spinbutton2A;
  GtkObject *spinbutton3A_adj;
  GtkWidget *spinbutton3A;
  GtkWidget *labelA4;
  GtkWidget *labelA7;
  GtkWidget *labelA9;
  GtkWidget *labelA3;
  GtkWidget *labelA6;
  GtkWidget *labelA8;
  GtkWidget *label3A10;
  GtkWidget *labelA13;
  GtkWidget *comboboxentry1A;
  GtkWidget *comboboxentry2A;
  GtkWidget *labelA11;
  GtkWidget *comboboxentryA;
  GtkWidget *labelA12;
  GtkWidget *buttonA1;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *labelA15;
  GtkWidget *buttonA2;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *labelA14;
  GtkWidget *buttonA3;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *labelA16;
  GtkWidget *labelA2;
  GtkWidget *filechooserbutton1A;
  GtkWidget *labelA5;
  GtkWidget *labelA1;
  GtkWidget *radiobutton1A;
  GSList *radiobutton1A_group = NULL;
  GtkWidget *radiobutton2A;

  Ajouter_un_entraineur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajouter_un_entraineur), _("Ajouter_un_entraineur"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (Ajouter_un_entraineur), fixed9);
  gtk_widget_set_size_request (fixed9, 704, 548);
  gtk_container_set_border_width (GTK_CONTAINER (fixed9), 10);

  entryA1 = gtk_entry_new ();
  gtk_widget_show (entryA1);
  gtk_fixed_put (GTK_FIXED (fixed9), entryA1, 152, 96);
  gtk_widget_set_size_request (entryA1, 264, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryA1), 8226);

  entryA2 = gtk_entry_new ();
  gtk_widget_show (entryA2);
  gtk_fixed_put (GTK_FIXED (fixed9), entryA2, 512, 96);
  gtk_widget_set_size_request (entryA2, 248, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryA2), 8226);

  entryA4 = gtk_entry_new ();
  gtk_widget_show (entryA4);
  gtk_fixed_put (GTK_FIXED (fixed9), entryA4, 496, 200);
  gtk_widget_set_size_request (entryA4, 248, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryA4), 8226);

  entryA5 = gtk_entry_new ();
  gtk_widget_show (entryA5);
  gtk_fixed_put (GTK_FIXED (fixed9), entryA5, 152, 432);
  gtk_widget_set_size_request (entryA5, 262, 38);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryA5), 8226);

  entryA6 = gtk_entry_new ();
  gtk_widget_show (entryA6);
  gtk_fixed_put (GTK_FIXED (fixed9), entryA6, 496, 248);
  gtk_widget_set_size_request (entryA6, 248, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryA6), 8226);

  calendar1A = gtk_calendar_new ();
  gtk_widget_show (calendar1A);
  gtk_fixed_put (GTK_FIXED (fixed9), calendar1A, 152, 152);
  gtk_widget_set_size_request (calendar1A, 262, 206);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1A),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  entryA3 = gtk_entry_new ();
  gtk_widget_show (entryA3);
  gtk_fixed_put (GTK_FIXED (fixed9), entryA3, 152, 376);
  gtk_widget_set_size_request (entryA3, 262, 38);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryA3), 8226);

  spinbutton1A_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1A = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1A_adj), 1, 0);
  gtk_widget_show (spinbutton1A);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton1A, 632, 472);
  gtk_widget_set_size_request (spinbutton1A, 46, 30);

  spinbutton2A_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton2A = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2A_adj), 1, 0);
  gtk_widget_show (spinbutton2A);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton2A, 680, 472);
  gtk_widget_set_size_request (spinbutton2A, 40, 32);

  spinbutton3A_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton3A = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3A_adj), 1, 0);
  gtk_widget_show (spinbutton3A);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton3A, 728, 472);
  gtk_widget_set_size_request (spinbutton3A, 40, 32);

  labelA4 = gtk_label_new (_("<b>Date de naissance</b>\n"));
  gtk_widget_show (labelA4);
  gtk_fixed_put (GTK_FIXED (fixed9), labelA4, 0, 160);
  gtk_widget_set_size_request (labelA4, 136, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelA4), TRUE);

  labelA7 = gtk_label_new (_("<b>E-mail</b>\n"));
  gtk_widget_show (labelA7);
  gtk_fixed_put (GTK_FIXED (fixed9), labelA7, 416, 208);
  gtk_widget_set_size_request (labelA7, 81, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelA7), TRUE);

  labelA9 = gtk_label_new (_("<b>CIN</b>"));
  gtk_widget_show (labelA9);
  gtk_fixed_put (GTK_FIXED (fixed9), labelA9, 424, 256);
  gtk_widget_set_size_request (labelA9, 57, 18);
  gtk_label_set_use_markup (GTK_LABEL (labelA9), TRUE);

  labelA3 = gtk_label_new (_("<b>Pr\303\251nom</b>"));
  gtk_widget_show (labelA3);
  gtk_fixed_put (GTK_FIXED (fixed9), labelA3, 432, 96);
  gtk_widget_set_size_request (labelA3, 72, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelA3), TRUE);

  labelA6 = gtk_label_new (_("<b>T\303\251l\303\251phone</b>"));
  gtk_widget_show (labelA6);
  gtk_fixed_put (GTK_FIXED (fixed9), labelA6, 8, 384);
  gtk_widget_set_size_request (labelA6, 88, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelA6), TRUE);

  labelA8 = gtk_label_new (_("<b>Adresse</b>"));
  gtk_widget_show (labelA8);
  gtk_fixed_put (GTK_FIXED (fixed9), labelA8, 16, 440);
  gtk_widget_set_size_request (labelA8, 72, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelA8), TRUE);

  label3A10 = gtk_label_new (_("<b>Sp\303\251cialit\303\251</b>"));
  gtk_widget_show (label3A10);
  gtk_fixed_put (GTK_FIXED (fixed9), label3A10, 8, 496);
  gtk_widget_set_size_request (label3A10, 88, 24);
  gtk_label_set_use_markup (GTK_LABEL (label3A10), TRUE);

  labelA13 = gtk_label_new (_("<b>Disponibilit\303\251</b>"));
  gtk_widget_show (labelA13);
  gtk_fixed_put (GTK_FIXED (fixed9), labelA13, 448, 408);
  gtk_widget_set_size_request (labelA13, 121, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelA13), TRUE);

  comboboxentry1A = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1A);
  gtk_fixed_put (GTK_FIXED (fixed9), comboboxentry1A, 576, 400);
  gtk_widget_set_size_request (comboboxentry1A, 80, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1A), _("Lundi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1A), _("Mardi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1A), _("Mercredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1A), _("Jeudi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1A), _("Vendredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1A), _("Samedi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1A), _("Dimanche"));

  comboboxentry2A = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry2A);
  gtk_fixed_put (GTK_FIXED (fixed9), comboboxentry2A, 688, 400);
  gtk_widget_set_size_request (comboboxentry2A, 71, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2A), _("matin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2A), _("midi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2A), _("soir"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2A), _("nuit"));

  labelA11 = gtk_label_new (_("<b>Ajouter une photo</b>"));
  gtk_widget_show (labelA11);
  gtk_fixed_put (GTK_FIXED (fixed9), labelA11, 432, 336);
  gtk_widget_set_size_request (labelA11, 145, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelA11), TRUE);

  comboboxentryA = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryA);
  gtk_fixed_put (GTK_FIXED (fixed9), comboboxentryA, 152, 480);
  gtk_widget_set_size_request (comboboxentryA, 262, 38);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryA), _("musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryA), _("gymnastique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryA), _("box"));
  gtk_combo_box_set_add_tearoffs (GTK_COMBO_BOX (comboboxentryA), TRUE);

  labelA12 = gtk_label_new (_("<b>Date de Fin de Contrat</b>\n"));
  gtk_widget_show (labelA12);
  gtk_fixed_put (GTK_FIXED (fixed9), labelA12, 456, 480);
  gtk_widget_set_size_request (labelA12, 168, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelA12), TRUE);

  buttonA1 = gtk_button_new ();
  gtk_widget_show (buttonA1);
  gtk_fixed_put (GTK_FIXED (fixed9), buttonA1, 552, 560);
  gtk_widget_set_size_request (buttonA1, 136, 48);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (buttonA1), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  labelA15 = gtk_label_new_with_mnemonic (_("<b>Annuler</b>"));
  gtk_widget_show (labelA15);
  gtk_box_pack_start (GTK_BOX (hbox15), labelA15, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (labelA15), TRUE);

  buttonA2 = gtk_button_new ();
  gtk_widget_show (buttonA2);
  gtk_fixed_put (GTK_FIXED (fixed9), buttonA2, 256, 560);
  gtk_widget_set_size_request (buttonA2, 144, 48);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (buttonA2), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  labelA14 = gtk_label_new_with_mnemonic (_("<b>Ajouter</b>"));
  gtk_widget_show (labelA14);
  gtk_box_pack_start (GTK_BOX (hbox14), labelA14, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (labelA14), TRUE);

  buttonA3 = gtk_button_new ();
  gtk_widget_show (buttonA3);
  gtk_fixed_put (GTK_FIXED (fixed9), buttonA3, 8, 0);
  gtk_widget_set_size_request (buttonA3, 134, 38);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (buttonA3), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  labelA16 = gtk_label_new_with_mnemonic (_("<b>Pr\303\251c\303\251dent</b>"));
  gtk_widget_show (labelA16);
  gtk_box_pack_start (GTK_BOX (hbox16), labelA16, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (labelA16), TRUE);

  labelA2 = gtk_label_new (_("<b>Nom</b>"));
  gtk_widget_show (labelA2);
  gtk_fixed_put (GTK_FIXED (fixed9), labelA2, 48, 104);
  gtk_widget_set_size_request (labelA2, 56, 16);
  gtk_label_set_use_markup (GTK_LABEL (labelA2), TRUE);

  filechooserbutton1A = gtk_file_chooser_button_new (_("S\303\251lectionner une photo"), GTK_FILE_CHOOSER_ACTION_OPEN);
  gtk_widget_show (filechooserbutton1A);
  gtk_fixed_put (GTK_FIXED (fixed9), filechooserbutton1A, 624, 312);
  gtk_widget_set_size_request (filechooserbutton1A, 128, 40);
  g_object_set (filechooserbutton1A,
                "show-hidden", TRUE,
                "width-chars", 1,
                NULL);

  labelA5 = gtk_label_new (_("<b>Sexe</b>\n"));
  gtk_widget_show (labelA5);
  gtk_fixed_put (GTK_FIXED (fixed9), labelA5, 416, 152);
  gtk_widget_set_size_request (labelA5, 72, 32);
  gtk_label_set_use_markup (GTK_LABEL (labelA5), TRUE);

  labelA1 = gtk_label_new (_("<span font=\"Poppins Bold 18\" >Ajouter un entraineur</span>"));
  gtk_widget_show (labelA1);
  gtk_fixed_put (GTK_FIXED (fixed9), labelA1, 280, 16);
  gtk_widget_set_size_request (labelA1, 320, 48);
  gtk_label_set_use_markup (GTK_LABEL (labelA1), TRUE);

  radiobutton1A = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton1A);
  gtk_fixed_put (GTK_FIXED (fixed9), radiobutton1A, 528, 144);
  gtk_widget_set_size_request (radiobutton1A, 124, 23);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1A), radiobutton1A_group);
  radiobutton1A_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1A));

  radiobutton2A = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton2A);
  gtk_fixed_put (GTK_FIXED (fixed9), radiobutton2A, 640, 144);
  gtk_widget_set_size_request (radiobutton2A, 124, 23);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2A), radiobutton1A_group);
  radiobutton1A_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2A));

  g_signal_connect ((gpointer) buttonA1, "clicked",
                    G_CALLBACK (on_buttonA1_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonA2, "clicked",
                    G_CALLBACK (on_buttonA2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajouter_un_entraineur, Ajouter_un_entraineur, "Ajouter_un_entraineur");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, entryA1, "entryA1");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, entryA2, "entryA2");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, entryA4, "entryA4");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, entryA5, "entryA5");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, entryA6, "entryA6");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, calendar1A, "calendar1A");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, entryA3, "entryA3");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, spinbutton1A, "spinbutton1A");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, spinbutton2A, "spinbutton2A");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, spinbutton3A, "spinbutton3A");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, labelA4, "labelA4");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, labelA7, "labelA7");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, labelA9, "labelA9");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, labelA3, "labelA3");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, labelA6, "labelA6");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, labelA8, "labelA8");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, label3A10, "label3A10");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, labelA13, "labelA13");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, comboboxentry1A, "comboboxentry1A");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, comboboxentry2A, "comboboxentry2A");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, labelA11, "labelA11");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, comboboxentryA, "comboboxentryA");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, labelA12, "labelA12");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, buttonA1, "buttonA1");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, image15, "image15");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, labelA15, "labelA15");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, buttonA2, "buttonA2");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, image14, "image14");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, labelA14, "labelA14");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, buttonA3, "buttonA3");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, image16, "image16");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, labelA16, "labelA16");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, labelA2, "labelA2");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, filechooserbutton1A, "filechooserbutton1A");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, labelA5, "labelA5");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, labelA1, "labelA1");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, radiobutton1A, "radiobutton1A");
  GLADE_HOOKUP_OBJECT (Ajouter_un_entraineur, radiobutton2A, "radiobutton2A");

  return Ajouter_un_entraineur;
}

GtkWidget*
create_Modifier_un_entraineur (void)
{
  GtkWidget *Modifier_un_entraineur;
  GtkWidget *fixed10;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkWidget *entry10;
  GtkWidget *entry11;
  GtkWidget *entry12;
  GtkWidget *calendar2;
  GtkWidget *entry13;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *labelM4;
  GtkWidget *buttonM3;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *labelM14;
  GtkWidget *labelM3;
  GtkWidget *labelM5;
  GtkWidget *labelM7;
  GtkWidget *labelM9;
  GtkWidget *filechooserbutton2;
  GtkWidget *labelM2;
  GtkWidget *comboboxentry5;
  GtkWidget *comboboxentry4;
  GtkWidget *labelM12;
  GtkWidget *comboboxentry6;
  GtkWidget *labelM6;
  GtkWidget *labelM8;
  GtkWidget *labelM10;
  GtkWidget *labelM1;
  GtkWidget *radiobutton4;
  GSList *radiobutton4_group = NULL;
  GtkWidget *radiobutton3;
  GtkWidget *labelM11;
  GtkWidget *labelM13;
  GtkWidget *buttonM2;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *labelM16;
  GtkWidget *buttonM1;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *labelM15;

  Modifier_un_entraineur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Modifier_un_entraineur), _("Modifier_un_entraineur"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (Modifier_un_entraineur), fixed10);
  gtk_widget_set_size_request (fixed10, 750, 550);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed10), entry8, 136, 96);
  gtk_widget_set_size_request (entry8, 264, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed10), entry9, 488, 88);
  gtk_widget_set_size_request (entry9, 248, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed10), entry10, 496, 192);
  gtk_widget_set_size_request (entry10, 248, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed10), entry11, 136, 432);
  gtk_widget_set_size_request (entry11, 272, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed10), entry12, 496, 240);
  gtk_widget_set_size_request (entry12, 248, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  calendar2 = gtk_calendar_new ();
  gtk_widget_show (calendar2);
  gtk_fixed_put (GTK_FIXED (fixed10), calendar2, 136, 144);
  gtk_widget_set_size_request (calendar2, 272, 208);
  gtk_calendar_display_options (GTK_CALENDAR (calendar2),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_fixed_put (GTK_FIXED (fixed10), entry13, 136, 376);
  gtk_widget_set_size_request (entry13, 272, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);

  spinbutton4_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbutton4, 616, 440);
  gtk_widget_set_size_request (spinbutton4, 40, 32);

  spinbutton5_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbutton5, 664, 440);
  gtk_widget_set_size_request (spinbutton5, 40, 32);

  spinbutton6_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbutton6, 712, 440);
  gtk_widget_set_size_request (spinbutton6, 40, 32);

  labelM4 = gtk_label_new (_("<b>Date de naissance</b>\n"));
  gtk_widget_show (labelM4);
  gtk_fixed_put (GTK_FIXED (fixed10), labelM4, 0, 160);
  gtk_widget_set_size_request (labelM4, 136, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelM4), TRUE);

  buttonM3 = gtk_button_new ();
  gtk_widget_show (buttonM3);
  gtk_fixed_put (GTK_FIXED (fixed10), buttonM3, 8, 0);
  gtk_widget_set_size_request (buttonM3, 120, 32);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (buttonM3), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  labelM14 = gtk_label_new_with_mnemonic (_("<b>Pr\303\251c\303\251dent</b>"));
  gtk_widget_show (labelM14);
  gtk_box_pack_start (GTK_BOX (hbox17), labelM14, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (labelM14), TRUE);

  labelM3 = gtk_label_new (_("<b>Pr\303\251nom</b>"));
  gtk_widget_show (labelM3);
  gtk_fixed_put (GTK_FIXED (fixed10), labelM3, 408, 96);
  gtk_widget_set_size_request (labelM3, 72, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelM3), TRUE);

  labelM5 = gtk_label_new (_("<b>Sexe</b>\n\n"));
  gtk_widget_show (labelM5);
  gtk_fixed_put (GTK_FIXED (fixed10), labelM5, 400, 144);
  gtk_widget_set_size_request (labelM5, 72, 32);
  gtk_label_set_use_markup (GTK_LABEL (labelM5), TRUE);

  labelM7 = gtk_label_new (_("<b>E-mail</b>\n"));
  gtk_widget_show (labelM7);
  gtk_fixed_put (GTK_FIXED (fixed10), labelM7, 408, 200);
  gtk_widget_set_size_request (labelM7, 81, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelM7), TRUE);

  labelM9 = gtk_label_new (_("<b>CIN</b>\n"));
  gtk_widget_show (labelM9);
  gtk_fixed_put (GTK_FIXED (fixed10), labelM9, 416, 248);
  gtk_widget_set_size_request (labelM9, 57, 18);
  gtk_label_set_use_markup (GTK_LABEL (labelM9), TRUE);

  filechooserbutton2 = gtk_file_chooser_button_new (_("S\303\251lectionner une photo"), GTK_FILE_CHOOSER_ACTION_OPEN);
  gtk_widget_show (filechooserbutton2);
  gtk_fixed_put (GTK_FIXED (fixed10), filechooserbutton2, 624, 312);
  gtk_widget_set_size_request (filechooserbutton2, 128, 40);
  g_object_set (filechooserbutton2,
                "show-hidden", TRUE,
                "width-chars", 1,
                NULL);

  labelM2 = gtk_label_new (_("<b>Nom</b>"));
  gtk_widget_show (labelM2);
  gtk_fixed_put (GTK_FIXED (fixed10), labelM2, 40, 104);
  gtk_widget_set_size_request (labelM2, 56, 16);
  gtk_label_set_use_markup (GTK_LABEL (labelM2), TRUE);

  comboboxentry5 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry5);
  gtk_fixed_put (GTK_FIXED (fixed10), comboboxentry5, 664, 384);
  gtk_widget_set_size_request (comboboxentry5, 87, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("matin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("midi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("soir"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry5), _("nuit"));

  comboboxentry4 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry4);
  gtk_fixed_put (GTK_FIXED (fixed10), comboboxentry4, 560, 384);
  gtk_widget_set_size_request (comboboxentry4, 96, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("Lundi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("Mardi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("Mercredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("Jeudi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("Vendredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("Samedi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("Dimanche"));

  labelM12 = gtk_label_new (_("<b>Date de Fin de Contrat</b>\n"));
  gtk_widget_show (labelM12);
  gtk_fixed_put (GTK_FIXED (fixed10), labelM12, 432, 448);
  gtk_widget_set_size_request (labelM12, 168, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelM12), TRUE);

  comboboxentry6 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry6);
  gtk_fixed_put (GTK_FIXED (fixed10), comboboxentry6, 136, 488);
  gtk_widget_set_size_request (comboboxentry6, 272, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("gymnastique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry6), _("box"));
  gtk_combo_box_set_add_tearoffs (GTK_COMBO_BOX (comboboxentry6), TRUE);

  labelM6 = gtk_label_new (_("<b>T\303\251l\303\251phone</b>"));
  gtk_widget_show (labelM6);
  gtk_fixed_put (GTK_FIXED (fixed10), labelM6, 32, 384);
  gtk_widget_set_size_request (labelM6, 88, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelM6), TRUE);

  labelM8 = gtk_label_new (_("<b>Adresse</b>"));
  gtk_widget_show (labelM8);
  gtk_fixed_put (GTK_FIXED (fixed10), labelM8, 40, 440);
  gtk_widget_set_size_request (labelM8, 72, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelM8), TRUE);

  labelM10 = gtk_label_new (_("<b>Sp\303\251cialit\303\251</b>"));
  gtk_widget_show (labelM10);
  gtk_fixed_put (GTK_FIXED (fixed10), labelM10, 32, 496);
  gtk_widget_set_size_request (labelM10, 88, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelM10), TRUE);

  labelM1 = gtk_label_new (_("<span font=\"Poppins Bold 18\">Modifier un entraineur</span>"));
  gtk_widget_show (labelM1);
  gtk_fixed_put (GTK_FIXED (fixed10), labelM1, 256, 16);
  gtk_widget_set_size_request (labelM1, 312, 48);
  gtk_label_set_use_markup (GTK_LABEL (labelM1), TRUE);

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed10), radiobutton4, 624, 144);
  gtk_widget_set_size_request (radiobutton4, 104, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed10), radiobutton3, 496, 144);
  gtk_widget_set_size_request (radiobutton3, 124, 23);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  labelM11 = gtk_label_new (_("<b>Ajouter une photo</b>\n"));
  gtk_widget_show (labelM11);
  gtk_fixed_put (GTK_FIXED (fixed10), labelM11, 424, 320);
  gtk_widget_set_size_request (labelM11, 145, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelM11), TRUE);

  labelM13 = gtk_label_new (_("<b>Disponibilit\303\251</b>"));
  gtk_widget_show (labelM13);
  gtk_fixed_put (GTK_FIXED (fixed10), labelM13, 424, 384);
  gtk_widget_set_size_request (labelM13, 121, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelM13), TRUE);

  buttonM2 = gtk_button_new ();
  gtk_widget_show (buttonM2);
  gtk_fixed_put (GTK_FIXED (fixed10), buttonM2, 208, 568);
  gtk_widget_set_size_request (buttonM2, 144, 48);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (buttonM2), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  labelM16 = gtk_label_new_with_mnemonic (_("<b>Modifier</b>"));
  gtk_widget_show (labelM16);
  gtk_box_pack_start (GTK_BOX (hbox19), labelM16, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (labelM16), TRUE);

  buttonM1 = gtk_button_new ();
  gtk_widget_show (buttonM1);
  gtk_fixed_put (GTK_FIXED (fixed10), buttonM1, 488, 568);
  gtk_widget_set_size_request (buttonM1, 136, 48);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (buttonM1), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  labelM15 = gtk_label_new_with_mnemonic (_("<b>Annuler</b>"));
  gtk_widget_show (labelM15);
  gtk_box_pack_start (GTK_BOX (hbox18), labelM15, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (labelM15), TRUE);

  g_signal_connect ((gpointer) buttonM2, "clicked",
                    G_CALLBACK (on_buttonM2_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonM1, "clicked",
                    G_CALLBACK (on_buttonM1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modifier_un_entraineur, Modifier_un_entraineur, "Modifier_un_entraineur");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, calendar2, "calendar2");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, labelM4, "labelM4");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, buttonM3, "buttonM3");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, image17, "image17");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, labelM14, "labelM14");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, labelM3, "labelM3");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, labelM5, "labelM5");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, labelM7, "labelM7");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, labelM9, "labelM9");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, filechooserbutton2, "filechooserbutton2");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, labelM2, "labelM2");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, comboboxentry5, "comboboxentry5");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, comboboxentry4, "comboboxentry4");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, labelM12, "labelM12");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, comboboxentry6, "comboboxentry6");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, labelM6, "labelM6");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, labelM8, "labelM8");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, labelM10, "labelM10");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, labelM1, "labelM1");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, labelM11, "labelM11");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, labelM13, "labelM13");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, buttonM2, "buttonM2");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, image19, "image19");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, labelM16, "labelM16");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, buttonM1, "buttonM1");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, image18, "image18");
  GLADE_HOOKUP_OBJECT (Modifier_un_entraineur, labelM15, "labelM15");

  return Modifier_un_entraineur;
}

GtkWidget*
create_Inscription____un_cours_ (void)
{
  GtkWidget *Inscription____un_cours_;
  GtkWidget *fixed11;
  GtkWidget *entry14;
  GtkWidget *entry15;
  GtkWidget *entry16;
  GtkWidget *treeview2i;
  GtkWidget *labeli1;
  GtkWidget *labeli2;
  GtkWidget *labeli3;
  GtkWidget *labeli4;
  GtkWidget *labeli5;
  GtkWidget *buttoni2;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *labeli9;
  GtkWidget *buttoni1;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *labeli10;
  GtkWidget *radiobutton1i;
  GSList *radiobutton1i_group = NULL;
  GtkWidget *radiobuttoni2;
  GtkWidget *buttoni3;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *labeli8;
  GtkWidget *comboboxentry7;
  GtkWidget *checkbuttoni1;
  GtkWidget *checkbuttoni2;

  Inscription____un_cours_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Inscription____un_cours_), _("Inscription_\303\240_un_cours"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (Inscription____un_cours_), fixed11);

  entry14 = gtk_entry_new ();
  gtk_widget_show (entry14);
  gtk_fixed_put (GTK_FIXED (fixed11), entry14, 72, 80);
  gtk_widget_set_size_request (entry14, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14), 8226);

  entry15 = gtk_entry_new ();
  gtk_widget_show (entry15);
  gtk_fixed_put (GTK_FIXED (fixed11), entry15, 408, 80);
  gtk_widget_set_size_request (entry15, 232, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15), 8226);

  entry16 = gtk_entry_new ();
  gtk_widget_show (entry16);
  gtk_fixed_put (GTK_FIXED (fixed11), entry16, 72, 144);
  gtk_widget_set_size_request (entry16, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry16), 8226);

  treeview2i = gtk_tree_view_new ();
  gtk_widget_show (treeview2i);
  gtk_fixed_put (GTK_FIXED (fixed11), treeview2i, 136, 304);
  gtk_widget_set_size_request (treeview2i, 400, 168);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (treeview2i), TRUE);

  GtkListStore *store;
  GtkTreeIter iter;
  const gchar *days[] = {"Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"};
  guint i;

  store = gtk_list_store_new(2, G_TYPE_STRING, G_TYPE_STRING);

  for (i = 0; i < G_N_ELEMENTS(days); i++) {
    // Add a row for "jour"
    gtk_list_store_append(store, &iter);
    gtk_list_store_set(store, &iter, 0, days[i], 1, "jour", -1);
    g_print("Adding: Day=%s, Period=jour\n", days[i]); // Debug print
    // Add a row for "nuit"
    gtk_list_store_append(store, &iter);
    gtk_list_store_set(store, &iter, 0, days[i], 1, "nuit", -1);
    g_print("Adding: Day=%s, Period=nuit\n", days[i]); // Debug print
  }

  gtk_tree_view_set_model(GTK_TREE_VIEW(treeview2i), GTK_TREE_MODEL(store));
  g_object_unref(store);




  GtkCellRenderer *renderer;
  GtkTreeViewColumn *column;

  renderer = gtk_cell_renderer_text_new ();
  column = gtk_tree_view_column_new_with_attributes (_("Jour"), renderer, "text", 0, NULL);
  gtk_tree_view_append_column (GTK_TREE_VIEW (treeview2i), column);

  renderer = gtk_cell_renderer_text_new ();
  column = gtk_tree_view_column_new_with_attributes (_("Période"), renderer, "text", 1, NULL);
  gtk_tree_view_append_column (GTK_TREE_VIEW (treeview2i), column);

  labeli1 = gtk_label_new (_("<span font=\"Poppins Bold 18\">Inscription \303\240 un cours sportif</span>"));
  gtk_widget_show (labeli1);
  gtk_fixed_put (GTK_FIXED (fixed11), labeli1, 144, 8);
  gtk_widget_set_size_request (labeli1, 384, 56);
  gtk_label_set_use_markup (GTK_LABEL (labeli1), TRUE);

  labeli2 = gtk_label_new (_("<b>Nom</b>"));
  gtk_widget_show (labeli2);
  gtk_fixed_put (GTK_FIXED (fixed11), labeli2, 16, 88);
  gtk_widget_set_size_request (labeli2, 57, 18);
  gtk_label_set_use_markup (GTK_LABEL (labeli2), TRUE);

  labeli3 = gtk_label_new (_("<b>Pr\303\251nom</b>"));
  gtk_widget_show (labeli3);
  gtk_fixed_put (GTK_FIXED (fixed11), labeli3, 312, 80);
  gtk_widget_set_size_request (labeli3, 89, 24);
  gtk_label_set_use_markup (GTK_LABEL (labeli3), TRUE);

  labeli4 = gtk_label_new (_("<b>CIN</b>"));
  gtk_widget_show (labeli4);
  gtk_fixed_put (GTK_FIXED (fixed11), labeli4, 8, 152);
  gtk_widget_set_size_request (labeli4, 57, 18);
  gtk_label_set_use_markup (GTK_LABEL (labeli4), TRUE);

  labeli5 = gtk_label_new (_("<b>Sp\303\251cialit\303\251</b>"));
  gtk_widget_show (labeli5);
  gtk_fixed_put (GTK_FIXED (fixed11), labeli5, 312, 152);
  gtk_widget_set_size_request (labeli5, 89, 24);
  gtk_label_set_use_markup (GTK_LABEL (labeli5), TRUE);

  buttoni2 = gtk_button_new ();
  gtk_widget_show (buttoni2);
  gtk_fixed_put (GTK_FIXED (fixed11), buttoni2, 208, 488);
  gtk_widget_set_size_request (buttoni2, 104, 40);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (buttoni2), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  labeli9 = gtk_label_new_with_mnemonic (_("<b>S'inscrire</b>"));
  gtk_widget_show (labeli9);
  gtk_box_pack_start (GTK_BOX (hbox22), labeli9, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (labeli9), TRUE);

  buttoni1 = gtk_button_new ();
  gtk_widget_show (buttoni1);
  gtk_fixed_put (GTK_FIXED (fixed11), buttoni1, 432, 488);
  gtk_widget_set_size_request (buttoni1, 104, 40);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (buttoni1), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  labeli10 = gtk_label_new_with_mnemonic (_("<b>Annuler</b>"));
  gtk_widget_show (labeli10);
  gtk_box_pack_start (GTK_BOX (hbox21), labeli10, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (labeli10), TRUE);

  radiobutton1i = gtk_radio_button_new_with_mnemonic (NULL, _("Mixte"));
  gtk_widget_show (radiobutton1i);
  gtk_fixed_put (GTK_FIXED (fixed11), radiobutton1i, 424, 216);
  gtk_widget_set_size_request (radiobutton1i, 124, 23);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1i), radiobutton1i_group);
  radiobutton1i_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1i));

  radiobuttoni2 = gtk_radio_button_new_with_mnemonic (NULL, _("Non Mixte"));
  gtk_widget_show (radiobuttoni2);
  gtk_fixed_put (GTK_FIXED (fixed11), radiobuttoni2, 536, 216);
  gtk_widget_set_size_request (radiobuttoni2, 124, 23);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttoni2), radiobutton1i_group);
  radiobutton1i_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttoni2));

  buttoni3 = gtk_button_new ();
  gtk_widget_show (buttoni3);
  gtk_fixed_put (GTK_FIXED (fixed11), buttoni3, 0, 0);
  gtk_widget_set_size_request (buttoni3, 128, 40);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (buttoni3), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  labeli10 = gtk_label_new_with_mnemonic (_("<b>Pr\303\251c\303\251dent</b>"));
  gtk_widget_show (labeli10);
  gtk_box_pack_start (GTK_BOX (hbox20), labeli10, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (labeli10), TRUE);

  labeli8 = gtk_label_new (_("<b>Date de Cours</b>"));
  gtk_widget_show (labeli8);
  gtk_fixed_put (GTK_FIXED (fixed11), labeli8, 256, 256);
  gtk_widget_set_size_request (labeli8, 144, 40);
  gtk_label_set_use_markup (GTK_LABEL (labeli8), TRUE);

  comboboxentry7 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry7);
  gtk_fixed_put (GTK_FIXED (fixed11), comboboxentry7, 408, 136);
  gtk_widget_set_size_request (comboboxentry7, 231, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("gymnastique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("box"));
  gtk_combo_box_set_add_tearoffs (GTK_COMBO_BOX (comboboxentry7), TRUE);

  checkbuttoni1 = gtk_check_button_new_with_mnemonic (_("Enfant"));
  gtk_widget_show (checkbuttoni1);
  gtk_fixed_put (GTK_FIXED (fixed11), checkbuttoni1, 80, 216);
  gtk_widget_set_size_request (checkbuttoni1, 117, 23);

  checkbuttoni2 = gtk_check_button_new_with_mnemonic (_("Adult"));
  gtk_widget_show (checkbuttoni2);
  gtk_fixed_put (GTK_FIXED (fixed11), checkbuttoni2, 160, 216);
  gtk_widget_set_size_request (checkbuttoni2, 117, 23);

  g_signal_connect ((gpointer) buttoni2, "clicked",
                    G_CALLBACK (on_buttoni2_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttoni1, "clicked",
                    G_CALLBACK (on_buttoni1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Inscription____un_cours_, Inscription____un_cours_, "Inscription____un_cours_");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, entry14, "entry14");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, entry15, "entry15");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, entry16, "entry16");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, treeview2i, "treeview2i");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, labeli1, "labeli1");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, labeli2, "labeli2");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, labeli3, "labeli3");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, labeli4, "labeli4");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, labeli5, "labeli5");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, buttoni2, "buttoni2");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, image22, "image22");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, labeli9, "labeli9");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, buttoni1, "buttoni1");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, image21, "image21");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, labeli10, "labeli10");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, radiobutton1i, "radiobutton1i");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, radiobuttoni2, "radiobuttoni2");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, buttoni3, "buttoni3");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, image20, "image20");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, labeli10, "labeli10");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, labeli8, "labeli8");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, comboboxentry7, "comboboxentry7");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, checkbuttoni1, "checkbuttoni1");
  GLADE_HOOKUP_OBJECT (Inscription____un_cours_, checkbuttoni2, "checkbuttoni2");

  return Inscription____un_cours_;
}

