/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ajout_ (void);
GtkWidget* create_modif_ (void);
GtkWidget* create_inscri_ (void);
GtkWidget* create_supp_ (void);
GtkWidget* create_Gestion_des_entraineur (void);
GtkWidget* create_Ajouter_un_entraineur (void);
GtkWidget* create_Modifier_un_entraineur (void);
GtkWidget* create_Inscription____un_cours_ (void);
